### ISSUE TITLE
First Release

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#194]
In preparation for a first release, here's a collection of todos needed for a minimal working chain. Add more items as they come up.

### Documentation
- [x] minimal tsdoc autogenerated docs #183 
- [ ] separate docs page, make it pretty w/ :heart: 
- [ ] add a QA section in order to make sure that our instructions to run Lodestar are as clear and easy to understand as possible

### Testing
- [ ] pass ssz spec tests
- [x] pass bls spec tests
- [ ] pass state transition spec tests
- [ ] unit tests for state transition utils

### Benchmarking
- [ ] add benchmarking framework
- [ ] benchmark block processing
- [ ] benchmark epoch processing
- [ ] benchmark ssz
- [ ] benchmark bls

### Eth1
- [ ] keep merkle tree of deposits #182 

### Chain
- [ ] unstub bls
- [ ] feed attestations into fork choice
- [ ] properly update state on fork choice decision
- [ ] update FFG checkpoints on epoch end
- [ ] perform any necessary cleanup after block processing ends

### OpPool
- [ ] unstub removal methods

### Sync
- [ ] initial sync
- [ ] "regular" sync

### Rpc
- [ ] add health checks

### Cli
- [ ] add option for configuration file #177 

### P2P
- [ ] broadcast blocks
- [ ] broadcast operations
- [ ] follow [libp2p standardization](https://github.com/ethereum/eth2.0-specs/pull/935), implement when ready
- [ ] add browser-compatible libp2p node #170 
- [ ] integrate [gossipsub](https://github.com/ChainSafe/gossipsub-js) when ready

### Node
- [ ] refactor as necessary for browser-specific node

### Validator
- [ ] unstub bls
- [ ] unstub rpc client #188 
- [ ] hook in attesting / block proposing logic
- [ ] save attestations to disk - [ensure we're never slashed](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/validator/0_beacon-chain-validator.md#how-to-avoid-slashing)

**Comment by Mikerah** [comment]
Should we also have a QA section in order to make sure that our instructions to run Lodestar are as clear and easy to understand as possible? This would include making sure that we can run Lodestar everywhere and that others can reliably run Lodestar on their machine.

**Comment by GregTheGreek** [comment]
We should probably note the difference in implementations for BLS -- milagro could be passing but herumi may not

**Comment by austinabell** [comment]
I'll look into implementing `add option for configuration file` #177. If anyone has any important information about how you would like it implemented, let me know!

**Comment by GregTheGreek** [comment]
> I'll look into implementing `add option for configuration file` #177. If anyone has any important information about how you would like it implemented, let me know!

Assigned!

**Comment by mpetrunic** [comment]
> We should probably note the difference in implementations for BLS -- milagro could be passing but herumi may not

We can run milagro implementation for now as it passes all the tests, and try to implement herumi later on.

As for benchmarking, we already have [profiler](https://github.com/winstonjs/winston#profiling) in winston logger.

**Comment by mpetrunic** [comment]
https://github.com/ChainSafe/lodestar/projects/11
