### ISSUE TITLE
[META] Startup Bug Tracking

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#200]
Current branch: `greg/expirement/start-beacon-chain`

I've begun to spin up lodestar with deposits, and tracking how the process of processing blocks. I'll be using this thread to document the issues I find along the way. Expect this thread to update frequently.

## **List of bugs**
- [x] effective_balance_increment #211 & #213 
- [x] Beacon --db flag #212
- [x] Update deposit contract [chainsafe/deposit_contract#4](https://github.com/chainsafe/deposit_contract/pull/4)
- [x] Deposit value is 0 #227 
- [ ] Deposit proof missing
- [x] Total deposits incorrect #227 
- [ ] Update deposit CLI paramaters
- [ ] BLS Private key as a uint8array / buffer

#### **Deposit**
- **commit:** `8356cde5a533126ede29bbb0cc429cf3efdd676e`
- **Start command:** `yarn build && ./bin/lodestar beacon --rpc "" --db test-db --eth1RpcUrl http://127.0.0.1:8545 --depositContract 0x8c594691C0E592FFA21F153a16aE41db5beFcaaa`
- **Eth1 Command:** `./bin/lodestar eth1:dev -m "vast thought differ pull jewel broom cook wrist tribe word before omit"`
- **Deposit Command:** `./bin/lodestar deposit -m "vast thought differ pull jewel broom cook wrist tribe word before omit" -n http://127.0.0.1:8545 -c 0x8c594691C0E592FFA21F153a16aE41db5beFcaaa`
- **Notes**: I commented out `sync` and `networking` modules for the time being
- **Error**: `verifyMerkleBranch` found in `stateTransition/util/misc.ts`. The `proof` command is an empty array and causing the app to throw with an unhandled promise rejection. 
- **Analysis**: ethers.ts line 203 states `//TODO: calculate proof` which is the probably cause for failure

#### **ETH1 Validator Deposit balance**
- Same config as **deposit config**
- **Error**: When a running `processDeposit()` the balance for the deposit is `0` and causing arithmetic errors.

#### **Beacon --db flag** 
- Same config as **deposit config**
- **Error**: The db flag condition had a strange bug where the flag exists but defaults to using the toml file

#### **Total Deposits**
- Once the genesis event begins, the BeaconState shows the total deposits to be 0 rather than 10 (in my simulation)

**Comment by GregTheGreek** [comment]
Found another bug, running the same config as above.

It seems that validator deposits are returning 0 from the ETH1 contract

**Comment by GregTheGreek** [comment]
EFFECTIVE_BALANCE_INCREMENT needs to be a Big number due BN.js issues when modding a number

**Comment by GregTheGreek** [comment]
Bug found with G2 Point in BLS-JS
```
(node:83779) UnhandledPromiseRejectionWarning: Error: The serialised input does not have the C flag set.
    at Function.fromCompressedBytes (/Users/gregmarkou/Jobs/code/github.com/ChainSafe/lodestar/node_modules/@chainsafe/bls-js/lib/helpers/g2point.js:126:15)
    at Function.fromCompressedBytes (/Users/gregmarkou/Jobs/code/github.com/ChainSafe/lodestar/node_modules/@chainsafe/bls-js/lib/signature.js:54:45)
    at Object.verify (/Users/gregmarkou/Jobs/code/github.com/ChainSafe/lodestar/node_modules/@chainsafe/bls-js/lib/index.js:95:34)
    at verify (/Users/gregmarkou/Jobs/code/github.com/ChainSafe/lodestar/src/chain/stateTransition/block/deposits.ts:65:14)
    at /Users/gregmarkou/Jobs/code/github.com/ChainSafe/lodestar/src/chain/genesis.ts:118:5
```
@mpetrunic

**Comment by mpetrunic** [comment]
Probably empty signatures, but true, verify method should catch invali signature and return false, will fix :)

**Comment by GregTheGreek** [comment]
Our deposit contract is out of date which was causing issues

**Comment by GregTheGreek** [comment]
Logs out of order:

`Chain initialized.` happened before all the deposits occured
```
2019-05-24 14:21:10 info: Setting up configurations...
2019-05-24 14:21:10 info: Starting eth2 beacon node - LODESTAR!
2019-05-24 14:21:10 info: Connected to LevelDB database at test-db
2019-05-24 14:21:10 info: Started listening on eth1 events on chain 1558722058821
2019-05-24 14:21:10 info: Listening for ETH2 genesis event...
2019-05-24 14:21:27 info: Received Eth2Genesis event. blockNumber=11, time=1558828800
2019-05-24 14:21:27 info: Initializing beacon chain...
2019-05-24 14:21:28 info: Received validator deposit event index=0
2019-05-24 14:21:28 info: Chain initialized.
2019-05-24 14:21:28 info: Received validator deposit event index=1
2019-05-24 14:21:28 info: Received validator deposit event index=2
2019-05-24 14:21:28 info: Received validator deposit event index=3
2019-05-24 14:21:29 info: Received validator deposit event index=4
2019-05-24 14:21:29 info: Received validator deposit event index=5
2019-05-24 14:21:29 info: Received validator deposit event index=6
2019-05-24 14:21:29 info: Received validator deposit event index=7
2019-05-24 14:21:29 info: Received validator deposit event index=8
2019-05-24 14:21:29 info: Received validator deposit event index=9
```

**Comment by mpetrunic** [comment]
> Logs out of order:

I thinks this is just because ganache is too fast and log processing takes longer than emitting genesis event. Won't happen with real network (except for deposit that triggered genesis maybe)

**Comment by GregTheGreek** [comment]
Closing as this is out of date
