### ISSUE TITLE
Light Client Hackathon TODO

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#2388]
Project public URL https://hack.ethglobal.co/showcase/lodestar-light-client-recElTbWnTEw2ehQL

- [x] 1. Light client server
  - [x] a. Light Client Update creation https://github.com/ChainSafe/lodestar/pull/2494
  - [x] b. Sync API - (depends on 1a) (Lion) https://github.com/ChainSafe/lodestar/pull/2494
  - [x] c. Proof API - Request/response proofs API and proof serialization (Cayman, PR open that will unblock a light client) 
- [x] 2. Light client client (able to hit consumer endpoints, sync state machine)
  - [x] a. Consume update and sync (Lion, simple/naive approach https://github.com/ChainSafe/lodestar/pull/2400) "fast" with mock backed https://github.com/ChainSafe/lodestar/pull/2494
  - [x] b. Consume proofs and display partial data (Cayman) https://github.com/ChainSafe/lodestar/pull/2493
  - [x] c. test sync and proof interaction https://github.com/ChainSafe/lodestar/pull/2494
  - [x] d. Combine into a website (no style, eg https://yieldfarming.info/) https://github.com/ChainSafe/lodestar/pull/2494
- [x] 3. Implement Altair fork on beacon node
  - [x] a. State transition
  - [x] b. State transition fast (optimize)(Cayman) https://github.com/ChainSafe/lodestar/pull/2508
  - [x] c. Update validator flow (Tuyen, refresh of block + attestation creation)
    - [x] 1. Beacon node server https://github.com/ChainSafe/lodestar/pull/2514 https://github.com/ChainSafe/lodestar/pull/2521 https://github.com/ChainSafe/lodestar/pull/2522
    - [x] 2. Validator client (includes adding sync committee services and extra signatures) https://github.com/ChainSafe/lodestar/pull/2520
  - [x] d. Networking
    - [x] 1. Gossip https://github.com/ChainSafe/lodestar/pull/2479 https://github.com/ChainSafe/lodestar/pull/2519
    - [x] 2. Request/response (Lion) https://github.com/ChainSafe/lodestar/pull/2444
    - [x] 3. Discv5 https://github.com/ChainSafe/lodestar/pull/2484

- [ ] 4. Bonus: Smuch it all together
  - [x] Add sim tests for Altair with ALTAIR_FORK_EPOCH = 0
  - [x] Add sim tests for Altair fork transition with ALTAIR_FORK_EPOCH = 2
  - [x] Run a local devnet with Altair
  - [x] Interop with Teku (already Altair capable)
  - [x] Implement Lightclient producer code (https://github.com/ChainSafe/lodestar/pull/2494) in the real BeaconNode

**Comment by twoeths** [comment]
Update: added `Discv5` to the networking part (3d).

**Comment by dapplion** [comment]
Includes https://github.com/ChainSafe/lodestar/issues/2085

**Comment by dapplion** [comment]
Completed
