### ISSUE TITLE
Lodestar Short Term TODO

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#2523]
Altair and Light Client
- [x] Finish stabilizing Altair 
- [x] Fix SSZ so it can handle proofs of entire subtrees
- [x] Take what we learned about the Light Client from building our prototype and report it to the eth2 spec repo
- [x] Upgrade to Alpha 4
- [x] Upgrade to Alpha 5
- [x] Upgrade to Alpha 6
- [x] connect our light client prototype and website to our actual Altair ready node
- [x] Spin up Altair testnet to interoperate with Teku 
- [ ] Reorg capable light client (can sync to the head) 
- [ ] Research and explore ways to extend consumable user data from L1 to L2.

Optimizations
- [x] Ship weak subjectivity sync 

Validator
- [x] Get our validator main net ready

**Comment by dapplion** [comment]
Continue tracking work with https://app.zenhub.com/workspaces/eth20-5c46babc258a903ed6f71597/issues/chainsafe/lodestar/2044
