### ISSUE TITLE
Amphora Tracking

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#3275]
Execution clients look here -> [Amphora README](https://github.com/ChainSafe/lodestar/tree/master/amphora)

## M1
> Spec Implemented

- [x] pass all released consensus test vectors https://github.com/ChainSafe/lodestar/issues/3076
- [x] run through engine [test vectors](https://notes.ethereum.org/@9AeMAlpyQYaAAyuj47BzRw/rkwW3ceVY) calling against geth - @dapplion 
- [x] run against [mergemock](https://github.com/protolambda/mergemock) - @tuyennhv 
- [x] Create Intro to Lodestar issue for other teams: e.g. Run these commands to start devnet with X config - @wemeetagain 
- [x] Run geth test vectors - @g11tech 

~~Add geth client into CI  @g11tech~~ (added by @dapplion )

## M2/M3
> 1-to-1 Interop – One EL and one CL team pair off for initial interop testing

- Team 1 - 
  - [x] run 1:1 devnet without transition (TTD == 0)  
  - [x] run 1:1 devnet with transition (TTD > 10)

- Team 2 - 
  - [ ] run 1:1 devnet without transition (TTD == 0)
  - [ ] run 1:1 devnet with transition (TTD > 10)

**Interoperability Status:**
*with execution*
- [x] Lodestar <> Geth  :hourglass_flowing_sand: 
- [x] Lodestar <> Besu  :hourglass_flowing_sand: 
- [ ] Lodestar <> Erigon  :hourglass_flowing_sand: 
- [x] Lodestar <> Nethermind  :hourglass_flowing_sand: 
- [x] Lodestar <> EthereumJS  :hourglass_flowing_sand: 

*with consensus*
- [ ] Lodestar <> Nimbus  :hourglass_flowing_sand: 
- [x] Lodestar <> Lighthouse  :hourglass_flowing_sand: 
- [ ] Lodestar <> Prysmatic  :hourglass_flowing_sand: 
- [x] Lodestar <> Teku  :hourglass_flowing_sand: 

## M4
> Many-to-Many Interop – 2 or more EL and CL teams perform interop testing

- [x] Run many:many devnet with transition (TTD > 50)
- [ ] Record teams and devnet config/results in separate issue

## M5
> All-to-All persistent devnet – All ready EL and CL teams create a long-lived devnet

- [x] Run many:many devnet with transition (TTD > 100)
- [x] Keep the devnet up for continuous testing and fun
- [ ] Create basic README for the public to connect

**Comment by dapplion** [comment]
I think we are only missing public instructions on how to run Lodestar with other execution clients

**Comment by dapplion** [comment]
Superseded by https://github.com/ChainSafe/lodestar/issues/3410
