### ISSUE TITLE
Memory Optimizations Tracker

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#3464]
# 📋  Milestone/Epic Tracker ![GitHub issues by-label](https://img.shields.io/github/issues/chainsafe/lodestar/scope-memory)
This tracker is to monitor outstanding issues and PRs relating to memory optimizations for Lodestar:

### 🟥  High Priority
- [ ] https://github.com/ChainSafe/lodestar/issues/3094
   - Prevent OOM
- [ ] https://github.com/ChainSafe/lodestar/issues/3137
- [ ] https://github.com/ChainSafe/lodestar/issues/3175

### 🟧  Medium Priority
- [ ] https://github.com/ChainSafe/lodestar/issues/3445
- [ ] https://github.com/ChainSafe/lodestar/issues/3510

### 🟨  Low Priority
- [ ] https://github.com/ChainSafe/lodestar/issues/2848
- [ ] https://github.com/ChainSafe/lodestar/issues/3039
- [ ] https://github.com/ChainSafe/lodestar/issues/3569
- [ ] https://github.com/ChainSafe/lodestar/issues/2848
- [ ] https://github.com/ChainSafe/lodestar/issues/2720

**Comment by philknows** [comment]
Not a scalable tracking solution for issues. Closing.
