### ISSUE TITLE
Light Client Planning Tracker

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#3469]
# 📋  Milestone/Epic Tracker ![GitHub issues by-label](https://img.shields.io/github/issues/chainsafe/lodestar/scope-lightclients)
This tracker is to monitor issues and PRs relating to light clients for Lodestar. This issue deprecates #2986. 
Lodestar's Light Client Demo: https://github.com/ChainSafe/eth2-light-client-demo

### 🟥  High Priority
- [x] https://github.com/ChainSafe/lodestar/issues/3952

### 🟧  Medium Priority
- [ ] https://github.com/ChainSafe/lodestar/issues/2985
- [x] https://github.com/ChainSafe/lodestar/issues/3079
- [ ] https://github.com/ChainSafe/lodestar/issues/3077
- [ ] https://github.com/ChainSafe/lodestar/issues/3618

## External Light Client References
- https://github.com/ethereum/consensus-specs/pull/2802
   - **For implementation**
- https://github.com/ethereum/beacon-APIs/pull/181
- https://github.com/ethereum/consensus-specs/pull/2267

---

### 1. Consensus Layer 
- Light client server: Allows head sync, but is censorable.
- Improve approaches to minimizing censorship (Multiple end servers, P2P layers (Portal Network?)
- Incentives Research (How do we find a way to prove real usage to compensate and incentivize running light client servers?)
Minimize censorable (End servers instead of one. Less censorable, P2P layer like portal?)
Incentives?? Find a way to prove real usage of a network with

### 2. Networking Layer
- Browsers not p2p friendly

### 3. Userland 
- Get useful data - L1 data (e.g. balances)
  - Query account balance + ERC20 balance: Pre-requisite https://github.com/ethereumjs/ethereumjs-monorepo/pull/1590

**Comment by holgerd77** [comment]
Hi guys,
could you drop the URL from your demo on the Lightclient Summit in Amsterdam here? 🙂

**Comment by dapplion** [comment]
> Hi guys, could you drop the URL from your demo on the Lightclient Summit in Amsterdam here? slightly_smiling_face

Added to the body! Also linking here Live demo: https://github.com/ChainSafe/eth2-light-client-demo

**Comment by philknows** [comment]
Not a scalable tracking solution for issues. Closing.
