### ISSUE TITLE
Lodestar v1.0.0-rc.0 Checklist

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#3538]
# 🏁  Milestone/Epic TO-DOs 
This epic is to track issues/features to be included for a fully featured `v1.0.0` release candidate. Our goal is to include these features for a release for the Goerli/Prater public testnet merge.

- [x] Complete Main Audit
- [x] Implement any fixes relating to the Main Audit for inclusion
- [x] Update documentation for `v1.0.0` candidate including post-merge configurations
- [x] Update setup guide v3 for post-merge configuration
- [x] Merge all Showstopper Items listed below

### 🟥  Pull Requests/Issues for Inclusion (Showstopper Items)
- https://github.com/ChainSafe/lodestar/issues/3945
- https://github.com/ChainSafe/lodestar/issues/3950
- https://github.com/ChainSafe/lodestar/issues/3682
  - https://github.com/ChainSafe/lodestar/issues/4063
- https://github.com/ChainSafe/lodestar/issues/4043
  - https://github.com/ChainSafe/lodestar/pull/4114
- https://github.com/ChainSafe/lodestar/issues/3689
  - https://github.com/ChainSafe/lodestar/pull/3883
- https://github.com/ChainSafe/lodestar/issues/3886
  - https://github.com/ChainSafe/lodestar/pull/4106
- https://github.com/ChainSafe/discv5/issues/158
- [ ] Any remaining internal issues

### 🟨  Optional Pull Requests/Issues
- To be discussed:  https://github.com/ChainSafe/discv5/issues/167

**Comment by philknows** [comment]
Lighthouse and Sigma Prime unable to do this. Reaching out to Teku.

**Comment by dadepo** [comment]
I would suggest we also include the key manager in the v1 freeze. It is a feature that is security related, as it touches on managing keys and also increases the external surface area of interaction with lodestar.

**Comment by philknows** [comment]
Based on the planning call on March 25, we're going to aim for most, if not all, current open PRs for inclusion by June. Any additional that come up and need to specifically be tracked will be added to this issue.

**Comment by philknows** [comment]
Closing in favour of using 

https://github.com/ChainSafe/lodestar/milestone/16 as a reference for audit inclusions.
https://github.com/ChainSafe/lodestar/milestone/17 as a reference for `v1.0.0` 

instead of doubling work in this issue.

**Comment by philknows** [comment]
Although not all items in this list made it to `v1.0.0`, they will be included with subsequent releases and re-prioritized based on needs + resources. Closing this specific tracker and will update roadmap with remaining items in here for future version releases.
