### ISSUE TITLE
Kiln 🔥🧱 (the merge) devnets 2022 tracker

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3731]
## Kiln 🔥🧱 

Kiln 🔥🧱  is the followup sprint of [Kintsugi :tea: ](https://github.com/ChainSafe/lodestar/issues/3452) with aim to move client implementations into the production readiness stage. This is the supposed to be last devnet before pre-production testsnets.

Kiln v1 spec: https://hackmd.io/@n0ble/kiln-spec
Kiln v2 spec: https://hackmd.io/@n0ble/kiln-spec#v2-change-set
Milestones tracker: https://notes.ethereum.org/@timbeiko/kiln-milestones
Engine API test vectors: https://notes.ethereum.org/rmVErCfCRPKGqGkUe89-Kg?view
### CL Spec Tracker 
- [CL spec 1.1.9](https://github.com/ChainSafe/lodestar/issues/3677)
#### Kiln v1:
- [x] Interface lodestar with the ELs on Kiln spec 1.0.0.alpha.6 https://github.com/ChainSafe/lodestar/pull/3736
- [x] basic interop with
  - [x] nethermind
  - [x] geth
- [x] #3751
- [x] devnet4 participation https://notes.ethereum.org/D5xK4XrmTb6MKGudf_hcrg
  - [x] setup of devnet by EL team
  - [x] Merge transition
  - [x] Issues/Observations 
    - This devnet was important for the EL's `beacon sync` apart from the changed api semantics. 
    - At the merge points, there were atleast 2 pow chains, and hence when the terminal block came in from the clients that were ahead, the lodestar node (whose EL  - nethermind was on another fork), got accepted and didn't move ahead  
    - Because of some issue (already being investigated by nethermind team), it didn't sync to right chain, with ACCEPTED status being rejected till the head of the chain (of synced ELs) move 128 slots ahead, after that it started syncing, and synced up to chain head with an execution status of syncing. Lodestar's behavior in this is as expected and as per the optimistic specs.
#### Kiln v2
- [x] https://github.com/ChainSafe/lodestar/pull/3777
- [x] Rename random to prevRandao https://github.com/ChainSafe/lodestar/pull/3787
~~- [ ] Add engine_exchangeTransitionConfigurationV1 https://github.com/ChainSafe/lodestar/pull/3785~~  moved to https://github.com/ChainSafe/lodestar/issues/3945

#### Devnet -5
- [x] https://github.com/ChainSafe/lodestar/pull/3821

#### Kiln
- [x] kiln network config update

#### [Kiln spec v2.1](https://hackmd.io/@n0ble/kiln-spec#v21-change-set )
- [x] https://github.com/ChainSafe/lodestar/pull/3855

**Comment by g11tech** [comment]
Closed in favour of the merge tracker: https://github.com/ChainSafe/lodestar/issues/3945
