### ISSUE TITLE
Lightclient wallet for ETH + ERC20 balances

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3796]
**Motivation**

Lodestar has so far developed a consensus lightclient that tracks the head with minimal resources. This is an important piece towards fully functional lightclients but doesn't have practical use for users. With the upcoming Amsterdam devconnect lightclient event https://lightclients.xyz/ it's very important to show the community the technical capabilities of lightclients today to rally support in this direction.

Browser based lightclients that support the full JSON RPC API require EVM execution with special SLOAD opcode that fetches storage dynamically. This is not an easy task, and it's being actively research by Portal Network participants https://github.com/ethereum/portal-network-specs. That's the long term goal, but meanwhile there are some valid use-cases that don't require EVM execution.

A read-only wallet that shows an account's ETH balance and ERC20 balances of well-known contracts doesn't require EVM execution since it can directly fetch storage slots at deterministic locations. This is what the main goal of this issue, and deploy it in Kintsugi / Klint testnets and then add p2p support for head tracking (upcoming).

**Todo**

In a web-app, or stand-alone library initially for easier testing:

- [ ] Import [lodestar's lightclient](https://github.com/ChainSafe/lodestar/tree/master/packages/light-client) and sync to the head. Existing implementation in https://github.com/ChainSafe/eth2-light-client-demo
- [ ] Request a consensus state proof to `latest_execution_payload_header.state_root`, with Lodestar proof API
- [x] Pre-compute execution state address of an account balance
- [x] Pre-compute execution state address of an account ERC20 balance and pre-selected contracts by the users
- [x] Request a execution state proof with [EIP-1186](https://eips.ethereum.org/EIPS/eip-1186) `eth_getProof`. Supported by Geth and [EthereumJS](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1590). Validate proof against `latest_execution_payload_header.state_root`

**Comment by g11tech** [comment]
UPDATE: got something rudimentary working for external addresses! https://github.com/ChainSafe/eth2-light-client-demo/pull/28
![image](https://user-images.githubusercontent.com/76567250/156573915-3f6153e9-191a-43f5-a877-2acb4beac0c6.png)

**Comment by dapplion** [comment]
Let's go! I can jump in latter and think of some design to show the info

**Comment by philknows** [comment]
Is there anything outstanding in here you want to continue tracking @dapplion ? Otherwise, we can create new issues and add to the #3469 light client tracker.

**Comment by dapplion** [comment]
@g11tech did a fantastic job here so we can close it. If we have more ideas to extend it further let's do new issues
