### ISSUE TITLE
Merge 🐼 Tracker

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3945]
This is a tracker to track and close out pending items/issues pertaining to EL <> CL merge

Mainnet merge
- [x] https://github.com/ChainSafe/lodestar/pull/4429

Pending items
- [x] https://github.com/ChainSafe/lodestar/pull/4182
- [x] https://github.com/ChainSafe/lodestar/pull/3958
- [x] https://github.com/ChainSafe/lodestar/pull/3965
- [x] https://github.com/ChainSafe/lodestar/pull/4340
- [x] https://github.com/ChainSafe/lodestar/pull/4450
- [x] https://github.com/ChainSafe/lodestar/issues/3946
- [x] https://github.com/ChainSafe/lodestar/pull/4350
- [x] https://github.com/ChainSafe/lodestar/pull/4362
- [x] https://github.com/ChainSafe/lodestar/pull/4411

Optimistic Sync
Feature Parity check: Upgrade to spec 1.2.0 https://github.com/ethereum/consensus-specs/pull/2896 
tracker: https://github.com/ChainSafe/lodestar/issues/4060
  - [x] #4360
     - https://github.com/ethereum/consensus-specs/pull/2869
     - Ensure compliance in error code finalized in PR when merged
     - https://github.com/ethereum/beacon-APIs/pull/216
  
Testing Frameworks
- [ ] https://github.com/ethereum/hive/pull/540 

Mev Tracker
- [x] https://github.com/ChainSafe/lodestar/pull/3969 extends #3958 and #3965

Some improvements/fixes:
- [x] https://github.com/ChainSafe/lodestar/pull/3854
- [x] https://github.com/ChainSafe/lodestar/pull/3930
- [x] https://github.com/ChainSafe/lodestar/pull/3912 dependency:  pending discussion on https://github.com/ChainSafe/node-snappy-stream/pull/3
- [x] https://github.com/ChainSafe/lodestar/pull/3949
- [x] https://github.com/ChainSafe/lodestar/pull/3963
- [x] https://github.com/ChainSafe/lodestar/pull/4016
- [x] https://github.com/ChainSafe/lodestar/issues/4054 https://github.com/ChainSafe/lodestar/pull/4209
- [x] https://github.com/ethereum/consensus-specs/pull/2891
- [x] https://github.com/ChainSafe/lodestar/pull/4058

Good to haves:
- https://github.com/ethereum/consensus-specs/pull/2875
- https://github.com/ChainSafe/lodestar/issues/3961
- https://github.com/ChainSafe/lodestar/issues/4208
- https://github.com/ChainSafe/lodestar/issues/3853

**Comment by philknows** [comment]
Question... is https://github.com/ethereum/consensus-specs/pull/2875 a joke or are we for real adding this as a feature @dapplion

**Comment by dapplion** [comment]
> Question... is [ethereum/consensus-specs#2875](https://github.com/ethereum/consensus-specs/pull/2875) a joke or are we for real adding this as a feature @dapplion

:panda_face:

**Comment by philknows** [comment]
@g11tech Likewise with #4060, should we compile remaining tasks here into https://github.com/ChainSafe/lodestar/issues/4455 ?

**Comment by g11tech** [comment]
> @g11tech Likewise with #4060, should we compile remaining tasks here into #4455 ?

sounds good to me! :+1:

**Comment by philknows** [comment]
Incomplete tasks have been compiled into #4455. Closing.
