### ISSUE TITLE
Mev Boost / flashbots integration tracker

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3953]
Currently its claimed that 80% of the pow mining rate (and hence potentially 80% of the pow blocks) could be MeV build block bundles.
Its proposed to natively integrate MeV with the CL clients for post merge block building, enabling solo stakers to integrate with the MeV ecosystem as well.

This is the tracker to document and track the MeV integration with lodestar
github: https://github.com/flashbots/mev-boost
architecture: https://hackmd.io/@flashbots/HJ3EbzVUY
implemenation overview: https://hackmd.io/@paulhauner/H1XifIQ_t#Change-2-Proposal-Promises
Specification 2.1: https://github.com/flashbots/mev-boost/blob/main/docs/specification.md

Tasks 
- [ ] setup the mev boost 
- [ ] sign and publish fee recipient to mev boost 
- [ ] call getheader on mevboost to get an execution header
- [ ] prepare, sign and publish a blind beacon block and fetch the full payload in response
