### ISSUE TITLE
Persist fork-choice state > start from head

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4000]
Currently Lodestar follow the simpler strategy (1) on start-up to just consider the latest finalized state as the head. Then sync all blocks from finalized state to head from our peers, and re-populate fork-choice graph.

Another strategy (2) is to persist the fork-choice state (on shutdown and / or periodically) and restore that state on startup. This approach will prevent "reverting" the head to a much older state. This caused:
- https://github.com/ChainSafe/lodestar/issues/3647
- https://github.com/ChainSafe/lodestar/issues/3717

**TODO**:
- [ ] Research what each other client is doing
- [ ] Estimate the positives of strategy (2) vs (1), specially in periods of long non-finality
- [ ] Estimate the complexity of strategy (2) vs (1), and the cost of persisting this data + pruning.

Only if it's clear that **positives >> complexity + cost**, consider implementing.

**Comment by g11tech** [comment]
my 2 cents: I actually like that we got, helps us recover lots of random scenarios by restarting, especially where local EL can be buggy in post-merge world by having this easy option to step back.

**Comment by wemeetagain** [comment]
👍 We should make sure this feature has an enable/disable flag
