### ISSUE TITLE
Validator performance improvements

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4001]
General **epic** to track all issues to improve validator performance and profitability:

Root: https://github.com/ChainSafe/lodestar/issues/3527

**On-going issues**

- [x] https://github.com/ChainSafe/lodestar/issues/3555
- [x] https://github.com/ChainSafe/lodestar/issues/3832
- [ ] https://github.com/ChainSafe/lodestar/issues/3907
- [ ] https://github.com/ChainSafe/lodestar/issues/3911
- [ ] https://github.com/ChainSafe/lodestar/issues/3922
- [x] https://github.com/ChainSafe/lodestar/issues/3940
- [ ] https://github.com/ChainSafe/lodestar/issues/3985
- [ ] https://github.com/ChainSafe/lodestar/issues/4028
- [ ] https://github.com/ChainSafe/lodestar/issues/4009

**Gossipsub issues**
- https://github.com/ChainSafe/js-libp2p-gossipsub/issues/249

**Additional metrics / tools**

- https://github.com/ChainSafe/lodestar/issues/3974

**Comment by dapplion** [comment]
Notes from https://discord.com/channels/613988663034118151/812268053718237196/935076545519845396

* more aggressive outgoing connections to increase the number of peers gossisub peers for every subnet (https://github.com/status-im/nimbus-eth2/pull/3241)
* shorter backoff so that resubscribing to an aggregation subnet works (https://github.com/status-im/nim-libp2p/pull/665) - this is important for people with 20+ validators on a single node
* disallow concurrent connections to the same peer (https://github.com/status-im/nimbus-eth2/pull/3241) - this prevents junk peers from taking up spots in the connection table and fixes some ordering bugs with subscription / unsubscription in the mesh

**Comment by twoeths** [comment]
note from Nimbus PR `3241` above:
- find subnet peer with outbound peers <`D_OUT` peers 
- or if we subscribe to a subnet, and < `D_LOW` mesh peers
- or subnets with topic peers < `D_LOW`(even if we don't subscribe to that subnet)
- or subnets with topic peers < `D_HIGH`

Given `GossipsubDout = 2` and we have too many outbound peers out of 50 (target) peers, we don't need that logic for now. It's nice to have other logic to find subnet peers, but we also have equivalent logic in lodestar so will consider this if we missed attestations.

With v0.36.0 and a mainnet node of 8 connected validators, topic peers look nice so no motivation to work on that right now

<img width="1265" alt="Screen Shot 2022-05-12 at 13 18 56" src="https://user-images.githubusercontent.com/10568965/168004637-2aaec922-c41a-44e3-b82a-ca828013cf9d.png">

**Comment by dapplion** [comment]
Almost all points covered, closing in favor of future more granular issues for specific improvements
