### ISSUE TITLE
Ensure feature parity with consensus spec v1.2.0

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4060]
Ensure we either have a PR or tracking issue (or mark as irrelevant) all features and changes in v1.2.0

Currently based on v1.2.0-rc.1 
- [ ] Update this issue when v1.2.0 is released

### Beacon chain

- [ ] Add new DomainType for application usage with "internal" namespace https://github.com/ethereum/consensus-specs/pull/2884

### Fork choice

- [x] #4303
  -  https://github.com/ethereum/consensus-specs/pull/2845
- [x] [Bugfix]  Require fork choice to run before proposal https://github.com/ethereum/consensus-specs/pull/2878 https://github.com/ethereum/consensus-specs/pull/2897
  - https://github.com/ChainSafe/lodestar/pull/4058
- [x] Update PROPOSER_SCORE_BOOST to 40 percent https://github.com/ethereum/consensus-specs/pull/2895

### Validator

- [ ] Update 0x01 withdrawal credentials to balance update (no code exec) https://github.com/ethereum/consensus-specs/pull/2854

### Networking

- [x] Ignore subset aggregates https://github.com/ethereum/consensus-specs/pull/2847
- [x] Ignore Aggregates Which Are Following the Wrong Finalized Checkpoint https://github.com/ethereum/consensus-specs/pull/2846
- [ ] Deprecate BeaconBlocksByRange.step https://github.com/ethereum/consensus-specs/pull/2856

### Light client
- [ ] Ensure light client optimistic_header to be at head. [ref](https://github.com/ethereum/consensus-specs/pull/2814)
- [ ] Consistently use compute_sync_committee_period. [ref](https://github.com/ethereum/consensus-specs/pull/2807)
- [ ] Implement p2p interface [ref](https://github.com/ethereum/consensus-specs/pull/2802)

### Fork choice

- [x] Add safe_block_hash and set to Justified https://github.com/ethereum/consensus-specs/pull/2851 https://github.com/ethereum/consensus-specs/pull/2858 https://github.com/ethereum/consensus-specs/pull/2876
  -  https://github.com/ChainSafe/lodestar/pull/4080 
- [x] Update PROPOSER_SCORE_BOOST to 40 percent https://github.com/ethereum/consensus-specs/pull/2895

### Optimistic sync

- [x] Optimistically import any post-merge block https://github.com/ethereum/consensus-specs/pull/2844
- [x] Remove justified block from optimistic candidate conditions https://github.com/ethereum/consensus-specs/pull/2881
  - PR: https://github.com/ChainSafe/lodestar/pull/4340 
- [x] Remove INVALID_TERMINAL_BLOCK https://github.com/ethereum/consensus-specs/pull/2891
  - PR : https://github.com/ChainSafe/lodestar/pull/4076
- [ ] Remove API restrictions for optimistic sync https://github.com/ethereum/consensus-specs/pull/2869

**Comment by philknows** [comment]
@g11tech Do we want to compile the remaining tasks in here for tracking in https://github.com/ChainSafe/lodestar/issues/4455 instead?

**Comment by philknows** [comment]
Incomplete tasks have been compiled into #4455. Closing.
