### ISSUE TITLE
Followup tracker for MeV related pending issues/cleanup

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4208]
This is a followup tracker for the 
 - https://github.com/ChainSafe/lodestar/pull/3969

#### Tasks
- [x]  [add the blinded variants to getForkTypes ](https://github.com/ChainSafe/lodestar/pull/3969#discussion_r907601731)
- [x] [blinded vs full block strategy] (https://github.com/ChainSafe/lodestar/pull/3969#discussion_r898818937)
- [x] https://github.com/ChainSafe/lodestar/pull/4703
- [x] Add metrics
~~- [ ] Validate the signature in signed builder bid received and validate for amount > min block rewards~~
- [x] https://github.com/ChainSafe/lodestar/pull/4488
- [x] [Do not create  a new validator registration data unless change in reg data](https://github.com/ChainSafe/lodestar/pull/4447)
  - this has been requested by the mev boost team to avoid load on relays, still send registrations but don't create new ones
  - ![image](https://user-images.githubusercontent.com/76567250/186832977-22ecb01a-33c3-484b-a497-deb6e98c3633.png)
