### ISSUE TITLE
Sim tests overhaul

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4275]
**Background**

_Sim test = running a full devnet for some time_

Sim tests are crucial to test blockchain nodes due to their complexity. Unit tests or e2e test never capture the complexity of the system when it's running at full capacity. Even then running a full devnet in CI is not sufficient to capture all bugs since some only appear under certain network size and / or conditions.

The scope and goals of sim tests in this repo should be:
- [x] Run small devnet for a relatively short period of time.
- [x] Capture a large amount of metrics to ensure good performance on all fronts.
- [x] Do so every commit, or at least on every commit of the main branch

Sim tests are (and will be) complemented by:
- [x] ~~Kurtosis testing: Run small devnets for short time but with all other client combinations. Medium level of assertions~~ Moved to #4772
- [x] ~~Hive testing: Run small devnets for short time but with unusual network conditions. Low level of assertions https://github.com/ChainSafe/lodestar/issues/4240~~ Moved to #4773
- [x] Deployment on Prater (beta testing): Run big devnet for long periods of time, but only infrequently before releases

**TODO**

Current sim test implementation is very old an subpar. It could be structured in a way that more modular, mantainable, and stable. However the first important step is to add assertions to cover the missing tick in the scope outline above:

- [x] Add proper assertions to sim tests https://github.com/ChainSafe/lodestar/issues/4276
- [x] Migrate leftover sim tests from e2e, to make e2e tests more stable and fast
- [x] Consolidate sim tests into less runs: do lightclient, finality, sync tests in one run https://github.com/ChainSafe/lodestar/issues/3931
- [x] Enable multi-node multi-process testing
  - Attempt at implementing https://github.com/ChainSafe/lodestar/pull/2575
  - Blocking issue https://github.com/ChainSafe/lodestar/issues/2542
- [x] ~~If expensive at this point, run in self-deployed GA runner.~~ **EDIT (nov 11th)**: keep the run light to work in Github runners

**Progressive improvements**
- [x] Log std to file, disable log to file. Enable DEBUG=* for Lodestar
- [x] Run Geth and Nethermind and test going through the merge, until finalizing merge block + 2 epochs
- [x] Ensure all nodes are connected to each other https://github.com/ChainSafe/lodestar/issues/4645
- [x] Once nodes reach untilEpoch, keep the chain running and spawn extra nodes to test syncing
  - [x] Start 1 node from genesis and range sync to head
  - [x] Start 1 node with checkpoint sync and sync to head  
- [x] Update the test timeout to be calculated [deterministically](https://github.com/ChainSafe/lodestar/pull/4673#discussion_r1007250212)
- [x] Disable the file logging for lodestar by explicitly setting it to `none`
- [x] Update the sync tests approach by just testing the sync behavior and not waiting for a particular epoch.

**Comment by nazarhussain** [comment]
While looking into following issue here is my initial observation. 

1. There is a lot of duplicate logic among the SIM tests and CLI 
2. Most of the related code is a kind of factories to create objects and configuration
3. Logic of creating objects is decoupled from the implementation, so the objects not aware what are the optimal way to create related options, configurations. 

I would suggest following approaches to improve: 

1. Create static implementations in the `BeaconNode` and `Validator` to create optimal defaults for the configurations and options. 
2. Reuse those static methods inside CLI and SIM tests. 
3. This way we will reuse a lot of logic and also code related to objects creation will stay along the objects. 

Other approach would be: 

1. To have separate private package for just for testing 
2. That package would consume just the CLI to create all relevant objects for testing 
3. We can refactor those CLI code to be easily reusable for testing 
4. This way we will be able to create nodes exactly the user will do with CLI 
5. We will reuse most of the initialization logic for nodes for the tests 
6. We will have one place for all SIM and in future E2E tests. 


Please share your thoughts.

**Comment by dapplion** [comment]
> To have separate private package for just for testing

We use to have this and it's not great. Tests should be placed in the package that has all the deps we need: either beacon-node or cli

**Comment by wemeetagain** [comment]
somewhat related: https://github.com/ChainSafe/lodestar/issues/4031
Not a private package, but test utilities def could be better organized for reuse

**Comment by dapplion** [comment]
> somewhat related: #4031 Not a private package, but test utilities def could be better organized for reuse

The initial idea of that package is to generate blocks and attesations valid for running tests without mocks. Since sim tests just run the full chain doesn't really apply

**Comment by nazarhussain** [comment]
We need to keep the issue open for the rest of the tasks.

**Comment by dapplion** [comment]
Expanding on "Migrate leftover sim tests from e2e, to make e2e tests more stable and fast"

By migrate I mean: cover the test / code paths with a successful sim test run and delete the e2e test.

- [x] Finalized sync test. This one should already be covered by current tests https://github.com/ChainSafe/lodestar/blob/d207b506252a52b0508a521ef0c1a840aff76715/packages/beacon-node/test/e2e/sync/finalizedSync.test.ts#L27
- [ ] Unknown block sync test. This one is not covered. What it does is set up a node without range sync and then manually import a block to the second node to trigger sync by unknown block parent https://github.com/ChainSafe/lodestar/blob/d207b506252a52b0508a521ef0c1a840aff76715/packages/beacon-node/test/e2e/sync/unknownBlockSync.test.ts#L30
- [x] WS sync test. This one should be covered already? https://github.com/ChainSafe/lodestar/blob/d207b506252a52b0508a521ef0c1a840aff76715/packages/beacon-node/test/e2e/sync/wss.test.ts#L25
- [ ] Lightclient sync + follow test. Not covered, should be doable to integrate https://github.com/ChainSafe/lodestar/blob/d207b506252a52b0508a521ef0c1a840aff76715/packages/beacon-node/test/e2e/chain/lightclient.test.ts#L48
