### ISSUE TITLE
Tracker: Improve Lodestar error UX 

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4400]
This is a tracker to collect all issues regarding to improving lodestar error UX. Most of the times we are pretty aggressive in throwing error even if its intermittent/self resolvable and requires no user action/attention.

For such issues, an error accumulator should be used and only throw if accumulator exceeds threshold (accum resets and starts from 0 if the progress is made between consecutive tries)

Issues:
- [x] Block Parent Unknown https://github.com/ChainSafe/lodestar/issues/3062#issuecomment-1211457758 as raised here https://github.com/ChainSafe/lodestar/issues/3062 and https://github.com/flashbots/mev-boost/issues/157
- [x] https://github.com/ChainSafe/lodestar/issues/4348
- [x] https://github.com/ChainSafe/lodestar/issues/5938
- [x] https://github.com/ChainSafe/lodestar/issues/4396
-  [x] https://github.com/ChainSafe/lodestar/issues/4146
-  [x] https://github.com/ChainSafe/lodestar/issues/3569
-  [x] https://github.com/ChainSafe/lodestar/issues/3605
-  [x] https://github.com/ChainSafe/lodestar/issues/4522
-  [x] https://github.com/ChainSafe/lodestar/issues/4523
-  [x] https://github.com/ChainSafe/lodestar/issues/2311
-  [x] https://github.com/ChainSafe/lodestar/issues/4540
-  [x] https://github.com/ChainSafe/lodestar/issues/4559

**Comment by dapplion** [comment]
Also this one, reported by Micah

```
Aug-11 07:37:06.001[]                 info: Synced - slot: 3641285 (skipped 2) - head: 3641283 0xfbcb…edb2 - execution: syncing(0x0631…0396) - finalized: 0xb07e…a3e6:113787 - peers: 47
Aug-11 07:37:18.000[]                 info: Synced - slot: 3641286 - head: 3641286 0x20b6…cf2a - execution: syncing(0xe143…c4d6) - finalized: 0xb07e…a3e6:113787 - peers: 47
Aug-11 07:37:24.112[NETWORK]         error: Gossip validation beacon_aggregate_and_proof threw a non-GossipActionError  Requesting slot committee out of range epoch: 113790 current: 113788
Error: Requesting slot committee out of range epoch: 113790 current: 113788
    at EpochContext.getShufflingAtEpoch (file:///usr/app/node_modules/@lodestar/state-transition/src/cache/epochContext.ts:669:13)
    at EpochContext.getShufflingAtSlot (file:///usr/app/node_modules/@lodestar/state-transition/src/cache/epochContext.ts:658:17)
```

**Comment by philknows** [comment]
Also tagging #4396, #4146 in here

**Comment by philknows** [comment]
https://github.com/ChainSafe/lodestar/issues/3569

EDIT (by @dapplion ) added all of these above in the main body

**Comment by nazarhussain** [comment]
All the tasks mentioned for this epic is closed.
