### ISSUE TITLE
Clean up deprecated stuff before next release

### ISSUE THREAD

**Issue by q9f** [ChainSafe/lodestar#4448]
- [x] remove `account` subcommand #4452
- [x] remove `kiln` testnet #4451
- [x] remove `prater` references, rename to `goerli` where applicable  #4451
- [x] remove `eth1.providerUrl`, use `eth1.providerUrls` where applicable https://github.com/ChainSafe/lodestar/pull/4457
