### ISSUE TITLE
Spec v1.2.0-rc.3 completion tracker

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4455]
Since v1.2.0-rc.3 introduce new test scenarios as well as `capella` hardfork, some of the test cases have been programmed to skip via PR https://github.com/ChainSafe/lodestar/pull/4456 and should be enabled as soon as they are supported/fixed.

This issue compiles incomplete changes up to v1.2.0-rc.3 and closes previous trackers https://github.com/ChainSafe/lodestar/issues/3945 and https://github.com/ChainSafe/lodestar/issues/4060

### Beacon chain

- [x] Add new DomainType for application usage with "internal" namespace https://github.com/ethereum/consensus-specs/pull/2884
  - https://github.com/ChainSafe/lodestar/pull/4542 

### Fork choice

- [x] https://github.com/ChainSafe/lodestar/issues/4303
  -  https://github.com/ethereum/consensus-specs/pull/2845
  - https://github.com/ChainSafe/lodestar/pull/4586
- [x] fix `forkchoice` - `discard_equivocations`

### Validator

- NA ~Update 0x01 withdrawal credentials to balance update (no code exec) https://github.com/ethereum/consensus-specs/pull/2854~
- [ ] fix `epoch processing` - `invalid_large_withdrawable_epoch`
- NA ~Validator status cleanup https://github.com/ethereum/consensus-specs/pull/280~

### Networking

- [x] Deprecate BeaconBlocksByRange.step https://github.com/ethereum/consensus-specs/pull/2856
  - #4499  

### Light client
- [ ] Ensure light client optimistic_header to be at head. [ref](https://github.com/ethereum/consensus-specs/pull/2814)
- [x] ~Consistently use compute_sync_committee_period. [ref](https://github.com/ethereum/consensus-specs/pull/2807)~ - does not require code changes. This is only a fix to the spec
- [x] Implement p2p interface [ref](https://github.com/ethereum/consensus-specs/pull/2802)
- [ ] Allow light client to verify signatures at period boundary https://github.com/ethereum/consensus-specs/pull/2805
- [x] Remove fork_version from LightClientUpdate https://github.com/ethereum/consensus-specs/pull/2916
- [ ] Allow LightClientUpdate with genesis finality https://github.com/ethereum/consensus-specs/pull/2924
- [ ] Allow passing redundant next_sync_committee https://github.com/ethereum/consensus-specs/pull/2927
- [x] Root next_sync_committee in attested_header https://github.com/ethereum/consensus-specs/pull/2932
- [x] Add LightClientBootstrap https://github.com/ethereum/consensus-specs/pull/2935
- [x] Add functions for deriving light client data https://github.com/ethereum/consensus-specs/pull/2938
- [x] Add LightClient(Finality|Optimistic)Update https://github.com/ethereum/consensus-specs/pull/2944
- [ ] Manually trigger LightClientStore force updates https://github.com/ethereum/consensus-specs/pull/2947
- [ ] ~Describe light client sync process https://github.com/ethereum/consensus-specs/pull/2951~ does not require code update from Lodestar part and can be removed from list, unless there is a reason to keep it here
- Tracked in sparate issue ~add `light_client` test runner and enable corresponding tests~

### Bellatrix
- [x] Merge mainnet ttd and bellatrix values https://github.com/ethereum/consensus-specs/pull/2969

### Optimistic Sync
- [x] How to apply latestValidHash when payload is INVALID https://github.com/ethereum/consensus-specs/pull/2954
- [x] Elaborate on why sync optimistically https://github.com/ethereum/consensus-specs/pull/2958
- [ ] extend optimistic node definition https://github.com/ethereum/consensus-specs/pull/2955
- [ ] Remove API restrictions for optimistic sync https://github.com/ethereum/consensus-specs/pull/2869
  - https://github.com/ChainSafe/lodestar/issues/4360
- [x] https://github.com/ethereum/consensus-specs/pull/2982

### MEV/Builder API
- Major issues addressed  ~https://github.com/ChainSafe/lodestar/issues/4208~

### Capella
- [x] add and enable `capella` hardfork

### Tests
- [x] fix `operations` - `voluntary_exit_with_previous_fork_version_is_before_fork_epoch__valid`
  - https://github.com/ChainSafe/lodestar/pull/4430 
- [x] `ssz_static`
- [ ] Testing framework: https://github.com/ethereum/hive/pull/540 

### Bugs
- [x] https://github.com/ChainSafe/lodestar/issues/3853

**Comment by dapplion** [comment]
@nazarhussain Currently skipped tests are

https://github.com/ChainSafe/lodestar/blob/13190d26ce562d2c5c0025706f2950b22586ce8e/packages/beacon-node/test/spec/utils/specTestIterator.ts#L51

Defined in:
- https://github.com/ethereum/consensus-specs/blob/dev/tests/formats/sync/README.md
- https://github.com/ethereum/consensus-specs/blob/dev/tests/formats/light_client/README.md

**Comment by dapplion** [comment]
Closing completed past spec tracker
