### ISSUE TITLE
Capella (withdrawals) hardfork integration tracker

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4571]
Tracker to integrated capella hardfork in lodestar
- [x] https://github.com/ChainSafe/lodestar/pull/4568
- [x]  https://github.com/ChainSafe/lodestar/pull/4707 https://github.com/ChainSafe/lodestar/pull/4730
  - [x] Replace bellatrix.ExecutionPayload/bellatrix.ExecutionPayloadHeader types by `allForks....` wherever meaningful
  - [x] Implement capella state upgrade
  - [x] handle `serializeExecutionPayload` ,`parseExecutionPayload` for capella
  - [x] handle execution_payload of `spec/presets/operations.ts`
  - [x] Handle genesis generation for capella
  - [x]  handle `capella` state gen in `beacon-node/test/util/state.ts`

Pending tasks:
- [x] test utils
  - [x] Check capella handling in `msgIdFn` fn in `gossip/encoding.ts`
  - [x] Add testcases for hardfork transition in `network/fork.test.ts`
- [x] handle `getInteropState` 's `latestPayloadHeader` assignment fork appropriate
- [x] Specs handle payload header type/assignment fork appropriate in
  - [x] in `initializeBeaconStateFromEth1` of `test/spec/presets/genesis.ts`
  - [x] enable in spec
- [x] Spec tests
  - [x]  add runners for `["full_withdrawals", "partial_withdrawals", "bls_to_execution_change", "withdrawals"]`
  - [x] `capella/random/random/pyspec_tests/randomized_11`, `capella/sanity/blocks/pyspec_tests`, full_withdrawal_in_epoch_transition"  (These tests specifically seem to have a full validator withdrawal with a validatorstill in sync committee. Remove once spec tests are fixed )
- [x] Implement Builder changes for capella (whenever they are available)

Major pending line items:

- [x] Handle gossips for blschange
- [x] implement the optimized withdrawal processing as and when PR is ready
- [x] Move to the new spec verison with queue current spec tests for capella has been disabled
  - [x] remove `MAX_PARTIAL_WITHDRAWALS_PER_EPOCH`, `WITHDRAWAL_QUEUE_LIMIT`
  - [x] change `MAX_WITHDRAWALS_PER_PAYLOAD` to 4 as per new without queue spec
- [x] add assetions in the withdrawal interop

**Comment by g11tech** [comment]
closing the tracker as the tasks look done :tada:
