### ISSUE TITLE
Pending spec test tracker

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4680]
Spec 1.3.0-alpha.0
- https://github.com/ChainSafe/lodestar/pull/4679
- https://github.com/ChainSafe/lodestar/pull/4707

has spec tests for 

- [x] `light_client`
- [x]  `sync` (most likely optimistic sync)
- [x]  add runners for 
  - [x] full_withdrawals" 
  - [x] "partial_withdrawals"
  - [x] "bls_to_execution_change"
  - [x] "withdrawals"
  - [x] "historical_summaries_update"
- [x] capella/random/random/pyspec_tests/randomized_11, capella/sanity/blocks/pyspec_tests, 
- [x] full_withdrawal_in_epoch_transition" (These tests specifically seem to have a full validator withdrawal with a validatorstill in sync committee. Remove once spec tests are fixed )
- [x] seek clarification on "eip4844/transition/core/pyspec_tests/transition_randomized_state" and fix runner or the test gets fixed

These spec runners need to be added into our spec test runner utils.

Completed:
- [x] handle genesis changes for the capella and enable genesis specs for capella

**Comment by g11tech** [comment]
closing as tasks are addressed
