### ISSUE TITLE
Lodestar prover for execution api

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4706]
### Description 

Execution land apps so far has been using JSON-RPC api (locally hosted or hosted by an infra or app provider). This places requirement of trust in the api provider which has lead to centralization of these services.

With ethereum PoS light client protocol, its now possible to verify the data served by the JSON-RPC `client` side. This creates a space for a "prover" library with which user can further decentralize trust.
Currently, a few provers a.la. kevlar and nimbus lc proxy have come up which basically offers a proxy to the web3 calls. This requires running another server which does the job of intercepting the calls to the backend rpc service and marry/prove it with the light client data.

However lodestar wants to approach it a bit differently. Lodestar wants to "programmatically" proxy so that the entire proving happens on the `client`. Obviously this can also be used to host a proxy rpc sever.

This  is the task for building such a module:

**ProofedProvider**
Takes a
  - a web3 provider  or options
  - a proofed root provider or options
 
and  returns a `safeProvider` which responses to the request with the proved data 

**Expected Usecase**

```typescript
import {ProofedWeb3Provider, ProofedRootProvider} from "@lodestar/prover"

const rpc:Web3Provider|URL = ....
const rootProvider: ProofedRootProvider|{mode: LightNode.Rest,apiUrl: string}|{mode: LightNode.P2P, bootnodes:string[]} = ....
const safeProvider = ProofedProvider(rpc ,rootProvider); 

// wait for safeProvider to sync 
await safeProvider.sync({checkpoint:"0x.."})

// you may stop query safe provider at any time synced or not
const {latest,finalized,status} = safeProvider.getStatus()

// you may call any web3 api at any time synced or not, but will error if number, latest. finalized can't be resolved
// calls by block root will not be proxided
safeProvider.eth_call(....)
safeProvider.eth_getBalance(...)
```

### Task List

- [x] Create a package skeleton `@lodestar/prover` 
- [x] Create a factory method to create a proofed web3 provider 
- [x] Create a factory method to create a proxy server 
- [x] Create a small CLI app to start the proxy and expose it as binary 
- [x] Add Rest interface for the lightclient 
- [x] Add P2P interface for the lightclient (Moved to https://github.com/ChainSafe/lodestar/issues/5644)
- [x] Optional logging support for the web3 provider 
- [x] Logging support for the proxy server to stream to std
- [x] Support to provide white list of fallback web3 methods for non-verified requests 
- [x] Check the given execution URLs for compatibility before start 
- [x] Run the e2e tests in the browser for the web3 provider (Covered with the existing browser tests)
- [x] Run the e2e tests in the Node for the web3 proxy (Moved to https://github.com/ChainSafe/lodestar/issues/5647)
- [x] Handle the re-org scenario for the proof provider (Moved to https://github.com/ChainSafe/lodestar/issues/5645)
- [x] Support batch RPC requests
- [x] Setup local EL/CL nodes for the CI
- [x] Use batch request inside `getExecutionPayloads` to optimize the performance 
- [x] Update all external requests to be restricted with timeout 
- [x] Update the logic for pruning the unfinalized headers (Moved to https://github.com/ChainSafe/lodestar/issues/5646)
- [x] Reduce dependency on etheruemjs packages (Out of scope for now)

### Web3 Methods to support 

The method support list is now moved to the [README](https://github.com/ChainSafe/lodestar/blob/unstable/packages/prover/README.md)

**Comment by philknows** [comment]
I think we should keep using this as a tracker for what has and hasn't been implemented yet for the entire scope of the prover @wemeetagain ?

**Comment by dapplion** [comment]
| Group | Method | Status
|-------|--------|----|
| Block | eth_getBlockByHash | ✅ done v0
|       | eth_getBlockByNumber | done v0
|       | eth_getBlockTransactionCountByHash | ⌛ todo v2
|       | eth_getBlockTransactionCountByNumber | todo v2
|       | eth_getUncleCountByBlockHash | todo v2
|       | eth_getUncleCountByBlockNumber | todo v2
| Chain/Network | eth_chainId | forward
|       | eth_syncing | todo v1
|       | eth_coinbase | todo v2
|       | eth_accounts | forward
|       | eth_blockNumber | forward
| Call and Estimate | eth_call | todo v0
|       | eth_estimateGas | todo v0
|       | eth_createAccessList | todo v2
|       | eth_gasPrice | todo v1
|       | eth_maxPriorityFeePerGas | todo v1
|       | eth_feeHistory | todo v2
| Filters | eth_newFilter | todo v2
|       | eth_newBlockFilter | todo v2
|       | eth_newPendingTransactionFilter | todo v2
|       | eth_uninstallFilter | todo v2
|       | eth_getFilterChanges | todo v2
|       | eth_getFilterLogs | todo v2
|       | eth_getLogs | todo v1
| Mining | eth_mining | forward
|       | eth_hashrate | forward
|       | eth_getWork | forward
|       | eth_submitWork | forward
|       | eth_submitHashrate | forward
| Signing | eth_sign | forward
|       | eth_signTransaction | forward
| State | eth_getBalance | done v0
|       | eth_getStorageAt | todo v1
|       | eth_getTransactionCount | todo v2
|       | eth_getCode | done v0
|       | eth_getProof | forward
| Transactions | eth_sendTransaction | forward
|       | eth_sendRawTransaction | forward
|       | eth_getTransactionByHash | todo v2
|       | eth_getTransactionByBlockHashAndIndex | todo v2
|       | eth_getTransactionByBlockNumberAndIndex | todo v2
|       | eth_getTransactionReceipt | todo v2

**Comment by nazarhussain** [comment]
The major tasks list is complete and few remaining are extracted to separate issues. So closing this epic issue.
