### ISSUE TITLE
Upgrade to node 18

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4768]
According to the [nodejs release schedule](https://github.com/nodejs/release#release-schedule), node 16 went into maintenance mode 2022-10-18.
The new active LTS is node 18.

We should upgrade all infrastructure, docs, guides, etc. to node 18.

Checklist for completing upgrade:
- [ ] CI/sim tests
- [ ] Docker builds 
- [ ] Individual dev environments
- [ ] Documentation upgrades
- [ ] Upgrade test/production fleet of servers

**Comment by philknows** [comment]
Targeting for next release if possible. We should keep an eye to see how it affects metrics/performance. Hopefully this helps with some of it.
