### ISSUE TITLE
EIP-4844 tracker

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4970]
## Implementation

- [x] Add params, config and types https://github.com/ChainSafe/lodestar/pull/4568
- [x] Make `c-kzg` library available for Lodestar. Add native bindings for `ethereum/c-kzg-eip4844` https://github.com/dankrad/c-kzg/pull/3
- [x] Block proposing
  - Add new engine API `engine_getBlobsV1`
  - Cache returned blobs in beacon to not modify validator cycle code
  - Publish to gossip topic, depending on fork
- [x] Block processing / import
  - Update chain `processBlock` to take block + (maybe) blobs pair
  - Validate blobs `is_data_available`, running KZG crypto
  - Store blobs to database + migrate from hot to cold on finalization + prune old blobs < MIN_EPOCHS_FOR_BLOBS_SIDECARS_REQUESTS
- [x] Add p2p ResResp methods `BeaconBlockAndBlobsSidecarByRoot` + `BlobsSidecarsByRange`
  - Update register / unregister logic to active those topics only post-eip4844
- [x] Add p2p gossip topic `beacon_block_and_blobs_sidecar`

Final PR

- https://github.com/ChainSafe/lodestar/pull/4774

## Devnet items

CC: @g11tech 

## Pending spec PRs

- [x] https://github.com/ethereum/consensus-specs/pull/3185
- [x] https://github.com/ethereum/consensus-specs/pull/3174
- [x] https://github.com/ethereum/consensus-specs/pull/3181
- [x] https://github.com/ethereum/beacon-APIs/pull/286

**Comment by g11tech** [comment]
closing in favour of https://github.com/ChainSafe/lodestar/issues/5279
