### ISSUE TITLE
Lodestar Integration into DappNode Tracker

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5044]
As part of our milestones to integrate Lodestar into more community-based initiatives, Lodestar will be integrated into DappNode as an additional onramp for users to try Lodestar as their consensus client. The package located here is the implementation which is currently continuing with our support.

This issue is to track the progress and any additional requirements needed to integrate Lodestar into DappNode's stack.

Current ongoing progress is located here: https://github.com/dappnode/DAppNodePackage-Lodestar

**Comment by wemeetagain** [comment]
@philknows @dapplion Is there anyone we can ping to help this along? we have PRs there sitting for a few weeks, don't want them to rot

**Comment by nflaig** [comment]
We need to get the goerli package to work first which is located here https://github.com/dappnode/DAppNodePackage-Lodestar-Prater. Can ignore the PRs on the other mainnet package for now as the changes will be ported over once the goerli package is tested. 

I tested the Lodestar package on goerli and it is broken at the moment, opened some PRs to fix the issues.

- https://github.com/dappnode/DAppNodePackage-Lodestar-Prater/pull/25
- https://github.com/dappnode/DAppNodePackage-Lodestar-Prater/pull/31
- https://github.com/dappnode/DAppNodePackage-Lodestar-Prater/pull/32
- https://github.com/dappnode/DAppNodePackage-Lodestar-Prater/pull/33
- https://github.com/dappnode/DAppNodePackage-Lodestar-Prater/pull/34

**Comment by nflaig** [comment]
Open tasks to finalize Lodestar x DAppNode integration

- [x] all 3 Lodestar packages are production ready, [DAppNodePackage-Lodestar](https://github.com/dappnode/DAppNodePackage-Lodestar), [DAppNodePackage-Lodestar-Prater](https://github.com/dappnode/DAppNodePackage-Lodestar-Prater), [DAppNodePackage-Lodestar-Gnosis](https://github.com/dappnode/DAppNodePackage-Lodestar-Gnosis) but still need to be officially published
- [x] https://github.com/dappnode/DNP_DAPPMANAGER/pull/1388 needs to be merged and mentioned packages in PR need to be published
- [x] https://github.com/dappnode/DNP_DAPPMANAGER/pull/1389 needs to be merged and released
- [x] PRs similar to https://github.com/dappnode/DNP_DAPPMANAGER/pull/1389 need to be created to add Lodestar to Gnosis and Mainnet to Stakers UI
- [x] https://github.com/dappnode/DNP_CORE/pull/127 needs to be merged and published
- [x] Verify all required changes (based on [this checklist](https://hackmd.io/YYZdWikXT72exnDOil7OUQ))  are done for each network (goerli/prater, gnosis, mainnet)

**Comment by alexpeterson91** [comment]
- [x] https://github.com/dappnode/DNP_DAPPMANAGER/pull/1419 needs to be merged and published
- [x] https://github.com/dappnode/DNP_DAPPMANAGER/pull/1418 needs to be merged and published
- [x] https://github.com/dappnode/DAppNodePackage-web3signer-gnosis/pull/49 needs to be merged and published
- [x] https://github.com/dappnode/DAppNode/pull/553 needs to be merged and published AFTER lodestar Mainnet is published
- [x] https://github.com/dappnode/DAppNodePackage-execution-multicaster/pull/5 Should be merged AFTER lodestar mainnet is published, doesnt need publishing yet as the package is not yet published publicly itself, just should merge this PR

**Comment by nflaig** [comment]
Lodestar integration tracker on dappnode side https://github.com/dappnode/DNP_DAPPMANAGER/issues/1422

**Comment by nflaig** [comment]
Lodestar is now officially supported on all networks, see  [release announcement](https://discord.com/channels/747647430450741309/770583149184155680/1100824182348075068)  🚀
