### ISSUE TITLE
Client monitoring integration tracker

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5095]
This issue is used to track updates required in other repositories to support Lodestar client monitoring implemented in #5037

- [x] Add Lodestar monitoring cli option to [eth-docker](https://github.com/eth-educators/eth-docker), e.g. see [lighthouse docker-entrypoint.sh](https://github.com/eth-educators/eth-docker/blob/bd2db055038b6a3a1f9cda322e05cb94efe7edee/lighthouse/docker-entrypoint.sh#L47) https://github.com/eth-educators/eth-docker/pull/1193
- [x]  Add Lodestar to [beaconcha.in user settings](https://github.com/gobitfly/eth2-beaconchain-explorer/blob/a9fa091bd06492aaa08c5339bcb314717494b018/templates/user/settings.html#L16), this is the [Mobile App section](https://beaconcha.in/user/settings#app) in accounts settings https://github.com/gobitfly/eth2-beaconchain-explorer/pull/1989, https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2180
- [x] Add Lodestar to [Mobile App <> Node Monitoring](https://kb.beaconcha.in/beaconcha.in-explorer/mobile-app-less-than-greater-than-beacon-node) docs https://github.com/gobitfly/eth2-knowledge-base/pull/31, https://github.com/gobitfly/eth2-knowledge-base/pull/34, https://github.com/gobitfly/eth2-knowledge-base/pull/35
- [x] Update [client support status](https://github.com/gobitfly/eth2-client-metrics-exporter#client-support-status) in [eth2-client-metrics-exporter](https://github.com/gobitfly/eth2-client-metrics-exporter) https://github.com/gobitfly/eth2-client-metrics-exporter/pull/7
- [x] Add Lodestar to [consensus client metrics](https://github.com/gobitfly/eth2-client-metrics#ethereum-consensus-client-metrics) docs https://github.com/gobitfly/eth2-client-metrics/pull/6
- [x] Rocket Pool monitoring integration ([monitoring-with-rocket-pool](https://kb.beaconcha.in/beaconcha.in-explorer/mobile-app-less-than-greater-than-beacon-node#monitoring-with-rocket-pool), [lighthouse example](https://github.com/rocket-pool/smartnode-install/blob/e3d7e656ecef92943fe3ac9948e1d215ab4a6e6e/install/scripts/start-bn.sh#L98))  https://github.com/rocket-pool/smartnode-install/pull/93 https://github.com/rocket-pool/smartnode/pull/335
- [x] Support client monitoring in [Lodestar Quickstart scripts](https://github.com/ChainSafe/lodestar-quickstart) https://github.com/ChainSafe/lodestar-quickstart/issues/12

**Comment by nflaig** [comment]
@philknows since we will release client monitoring with `v1.6.0` we should make sure that all integrations are also kept up-to-date. Besides the ones I already linked in the issue, is there anything else that comes to your mind?
