### ISSUE TITLE
Deneb tracker

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#5279]
TODOs
 - [x] https://github.com/ChainSafe/lodestar/issues/6257
 - [ ] remove state regen in validations for both block and blob see comment here: https://github.com/ChainSafe/lodestar/pull/6087#discussion_r1399674822
 - [x] add and use an independent event in case of blob availability promise not resolving in a threshold see comment here : https://github.com/ChainSafe/lodestar/pull/6087#discussion_r1400137384
 - [x] finalize the optimistic blob wait strategy https://github.com/ChainSafe/lodestar/pull/6087#discussion_r1420896679
 - [ ] review config and preset fields
   - [x] ~~use blob subnet count rather than max blobs per block to setup gossip~~ peerDAS will complete overhaul this
 - [x] any other cleanup?
   - [x] produceblockv3 cleanup
     - [x] cleanup builder selection from beacon/apis (and handle only in validator)
     - [x] move engine selection confition logic to  a fn https://github.com/ChainSafe/lodestar/pull/6236#discussion_r1444901564
     - [x]   using toString for bigint serialization to winston then `varname` pattern https://github.com/ChainSafe/lodestar/pull/6236#discussion_r1444900338
     - [x] remove hardcoded bigint(100) with bigint_100 kind of constant https://github.com/ChainSafe/lodestar
/pull/6236#discussion_r1444928361
     - [x] in logs slot should come first (https://github.com/ChainSafe/lodestar/pull/6258/files#r1444649796)  also review log order of other vars
 - [ ] spec test runners
   - [ ] kzg test
   - [ ] merkle proof 
 - [x] block production changes
   - [x] https://github.com/ChainSafe/lodestar/pull/6236
   - [x] https://github.com/ChainSafe/lodestar/pull/6258 

#### devnet 12
- [x] https://github.com/ChainSafe/lodestar/pull/6087
- [x] https://github.com/ChainSafe/lodestar/pull/6089
  - [x] builder api for blobsidecars with inclusion

#### Old Work
- [x] https://github.com/ChainSafe/lodestar/pull/5181
- [x] https://github.com/ChainSafe/lodestar/pull/5933
- [x] enable skipped spec tests
  - [x] deneb fork 
  - [x] forkchoice spec tests by fixing "safe slots to justified" removal  https://github.com/ChainSafe/lodestar/pull/5126

### Devnets
- [x] devnet5 Specs https://hackmd.io/@inphi/HJZo4vQGn lodestar PR/branch: https://github.com/ChainSafe/lodestar/pull/5181
  - [x] https://github.com/ethereum/consensus-specs/pull/3317
  - [x] https://github.com/ethereum/consensus-specs/pull/3244
  - [x] https://github.com/ethereum/execution-apis/pull/392
  - [x] https://github.com/ethereum/beacon-APIs/pull/302
  - [x] https://github.com/ethereum/execution-apis/pull/402
- [x] devnet6/7 
- [x] devnet 8
  - [x] https://github.com/ChainSafe/lodestar/pull/5724
  - [x] parent beacon block root
- [x] devnet 9 
- [x] Code TODOs
  - [x] https://github.com/ChainSafe/lodestar/pull/5929

**Comment by philknows** [comment]
For persisting the deprecation of `exchangeTransitionConfiguration` 
https://hackmd.io/@n0ble/deprecate-exchgTC

**Comment by g11tech** [comment]
unpinning the issue but keeping it alive for some of the cleanup/optimization items
