### ISSUE TITLE
Lodestar 2023 Q1 roadmap

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5381]
Main focus: increase adoption

### Increase adoption
- [x] Complete security audit
- [x] Add to launchpad
- [x] Integrate with RocketPool https://github.com/ChainSafe/lodestar/issues/3687
- [x] Integrate with DAppNode https://github.com/ChainSafe/lodestar/issues/5044

### Lightclient
- [x] Capella compatibility https://github.com/ChainSafe/lodestar/pull/5027 https://github.com/ChainSafe/lodestar/issues/5102
- [ ] Lodestar light (PoS) https://github.com/ChainSafe/lodestar/issues/4705

### Network features
- [x] Develop capella HF https://github.com/ChainSafe/lodestar/issues/5245
- [ ] Develop deneb HF https://github.com/ChainSafe/lodestar/issues/5279

**Comment by philknows** [comment]
Closing for #5382
