### ISSUE TITLE
Lodestar 2023 Q2 roadmap

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5382]
Main focus: lightclient

Lightclient:
- [x] Browser based prover with quasi complete support for JSON RPC API https://github.com/ChainSafe/lodestar/issues/4706
- [ ] Publicly available infrastructure for consensus layer arbitrary proofs of any state
- [ ] Write spec for slashing options
- [ ] Ligthclients in L2 research
- [ ] Consensus browser based lightclient over p2p

Retain adoption:
- [x] Improve user logging UX
- [ ] Good peering and stable mesh in almost all cases
- [ ] Increase average rated.network effectiveness from 93% -> to node operator average (~95%)

Network features
- [ ] Develop deneb HF https://github.com/ChainSafe/lodestar/issues/5279
- [ ] In-protocol deposits https://github.com/ChainSafe/lodestar/issues/5366

Misc / optimizations / debt
- [x] Move libp2p instance to a worker thread #5447
- [ ] Working PoC BLST on v8 thread pool
- [ ] Good altruistic network peer (fast forward times, back-fill)

**Comment by philknows** [comment]
Closing for #5751
