### ISSUE TITLE
Update to Nodejs v20

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#5611]
### Problem description

Nodejs v20 is released and holds promise to be somewhat more performant (possibly resolving #4903)

### Solution description

Update to v20, resolving any build issues that arise.

- [x] blst https://github.com/ChainSafe/lodestar/pull/5612
- [x] cpu_features https://github.com/ChainSafe/lodestar/pull/5674
- [x] snappy https://github.com/ChainSafe/lodestar/pull/5617
- [x] gc-stats https://github.com/ChainSafe/lodestar/pull/5677 https://github.com/ChainSafe/lodestar/pull/5683 https://github.com/ChainSafe/lodestar/pull/5686 https://github.com/ChainSafe/lodestar/pull/5690

**Comment by philknows** [comment]
Would also do a quick scan of the documentation to ensure anywhere we state node requirements to use node 20.

**Comment by wemeetagain** [comment]
`unstable` branch with Node 20 has been deployed to our `feat1` group for several days

**Comment by wemeetagain** [comment]
Closed with 1.10.0
