### ISSUE TITLE
Add P2P interface for the lightclient

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#5644]
### Problem description

Currently the light-client is connected to beacon-node via REST api. Which is good but not yet depend on a central node. 

### Solution description

We need to introduce P2P interface for the light-client to connect to bootnodes to improve decentralization. 

### Additional context

This issue was extracted from https://github.com/ChainSafe/lodestar/issues/4706

**Comment by OtowoSamuel** [comment]
Hi, @nazarhussain can i be assigned this issue?

**Comment by Bratipah** [comment]
Hey @nazarhussain I'm form women in ethereum protocol (WIEP) cohort 4 and i'm requesting if i can be assigned this issue. I have been able to go through the Lodestar prover purpose and vision and the reason for the proxy. Looking forward to start on the p2p interface . I've also been able to run the light client within the project to understand the issue better

**Comment by philknows** [comment]
Feel free to chat with us in our Discord @Bratipah if you have additional questions for Nazar or others!

**Comment by 0xmrree** [comment]
Doesn't appear anyone is still working on this, so i'm gonna take a crack at this week. (let me know if this is not the case) i'm sure I will have questions and all post in discord.

**Comment by matthewkeil** [comment]
> Doesn't appear anyone is still working on this, so i'm gonna take a crack at this week. (let me know if this is not the case) i'm sure I will have questions and all post in discord.

Sounds good.  Its all yours!!

**Comment by 0xmrree** [comment]
# Current progress

### Research stuff - ramp up - eta 02/09/2025
- [x] How does the light client protocol work to trustlessly get finalized checkpoint root and optimistic head root - [see](https://discord.com/channels/593655374469660673/1460150128307601469/1461938894395281556) 
- [x] What is the libp2p stack and how is it used specially in eth for gossipsub / reqresp protocols - [see](https://discord.com/channels/593655374469660673/1460150128307601469/1466986638977667082)
- [x] How generally does gossip work on top of libp2p stream -  [see](https://discord.com/channels/593655374469660673/1460150128307601469/1467269847162421441)
- [x] How does req resp protocol work on top of libp2p stream
- [x] How do eth subnets work, why they are used, and will they need to be considered for lightclient - [see](https://discord.com/channels/593655374469660673/1460150128307601469/1467278646287794187)
Subnets are used for the attestations but not for `light_client_optimistic_update` and `light_client_finality_update`. Even those messages have a ton of publishers at once, they are publishing the same message which scales nicely with libp2p caching. You only need the subnets when the messages published at once are different.
- [x] How are eths phase0 messages (Ping,Status,Metadata, and Goodbye) used? - [see](https://github.com/0xmrree/ethereum-simulator/blob/main/docs/loadstar/networking/ETHEREUM_PROTOCOL_MESSAGES.md) 
- [x] How should LC handle incoming non phase 0 req reps - We need to remove handlers and ensure when/if a peers sets up `/ipfs/id/1.0.0` we don't claim to support those non phase 0 protocols. If we advertise we do
- [x] How does beacon node bootstraping work with peer status and metadata exchange checks 
- [ ] Understand how beacon nodes gets away without given peers that don't support non phase0 req resp messages yet is still able to sync. 
- [ ] Create a high level class diagram of main network components and **basic** descriptions of each component 
- [ ] Understand how the current network threading setup works and how it will working in LC
- [ ] What (if any) peer scoring modifications need to be made for LC
- [ ] What (if any) discv5 enr check modifications need to be made for LC
- [x] Does light client have to handle specially the fact we don't participate in any sync/att subnets  - **no**
beacon nodes without validator clients also wont participate in subnets yet still are able to not get immediately booted from others peers lists. Its just that under high network demands we will be booted *first from others peers lists 
- [x] Can we use optimistic head for Status message head root / slot - Yes peers shouldn't care as it would be if we just have a super slow network connected given the optimistic head will always be behind a beacon nodes head

### Implementation
todo

### Testing
todo

**Comment by 0xmrree** [comment]
https://github.com/0xmrree/lodestar/tree/light-client-p2p-v2
### Implementation 
- [x] Pull in the existing clock and setup p2p identity 
- [x] Setup network config via cli init phase - lets forget bootnode file for p0, not reuse beacon node options 
- [x] Move out shared /spec code to avoid circular dependency with LC <-> beacon 
- [x] Simplify network core/facade to not have multi-threaded support (`useWorker=false`), then start pulling in dependencies - gonna remove prometheus stuff
- [x] Remove the attestation and sync committee services (and any PeerDAS custody stuff) from core since we don't need to populate our peers based on VC duties - given peer manager handles empty active attnets/syncnets we can just create noop versions of services and remove and subnet preparing methods from network code
- [ ] For Network Processor - fork to work without chain or db - For gossipsub, implement LC-specific IGNORE and REJECT validation logic for the two gossip topics: light_client_optimistic_update and light_client_finality_update
- [x] For all non-Phase 0 Req/Resp handlers, refactor to always return status 3 (ResourceUnavailable) and empty list for SSZ list types - fork ReqRespBeaconNode to ReqRespLightClient
- [x] For Phase 0 Req/Resp:
  - [x] **Ping**: leave as is
  - [x] **Metadata**: make sure to not advertise that we participate in any subnets
  - [x] **Status**: use genesis root/slot for finalized and head data - this is specifically called out in the spec to limit the chance we get called for our ResourceUnavailable methods
- [x] For Req/Resp collectors (handling incoming responses), we won't have to make any changes
- [ ] Properly source network options via cli
- [ ] Wire all components together into the transport interface

todos after lc p2p:
-  beacon node - make send goodbye not block for peers goodbye
- why does BeaconBlocksByRoot not have validation?
