### ISSUE TITLE
Beacon API v3.0.0 spec compliance

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5710]
To be compliant to latest beacon API spec ([v3.0.0](https://github.com/ethereum/beacon-APIs/releases/tag/v3.0.0-alpha.9)) several updates are required.

# v3.0.0

- [x] https://github.com/ChainSafe/lodestar/issues/6895

# v2.5.0

- [x] https://github.com/ChainSafe/lodestar/issues/6470
- [x] https://github.com/ChainSafe/lodestar/issues/6058

# v2.4.2

- [x] https://github.com/ChainSafe/lodestar/issues/6185

# v2.4.1

*Nothing*

# v2.4.0

- [x] Ensure operationIds match spec value
- [x] https://github.com/ChainSafe/lodestar/issues/5693
- [x] https://github.com/ChainSafe/lodestar/issues/5542
- [x] https://github.com/ChainSafe/lodestar/issues/5694
- [x] https://github.com/ChainSafe/lodestar/issues/5696
- [x] https://github.com/ChainSafe/lodestar/issues/5698
- [x] https://github.com/ChainSafe/lodestar/issues/4935
- [x] https://github.com/ChainSafe/lodestar/issues/5699
- [x] https://github.com/ChainSafe/lodestar/issues/5700
- [x] https://github.com/ChainSafe/lodestar/issues/5701
- [x] https://github.com/ChainSafe/lodestar/issues/5702
- [ ] https://github.com/ChainSafe/lodestar/issues/4638
- [x] https://github.com/ChainSafe/lodestar/issues/6167
- [x] https://github.com/ChainSafe/lodestar/issues/6168
- [x] https://github.com/ChainSafe/lodestar/issues/6170
- [x] https://github.com/ChainSafe/lodestar/issues/6480
- [x] https://github.com/ChainSafe/lodestar/issues/6293

All the above issues can be tackled independently. A PR that implements a new API or adds new parameters needs to make sure to update the corresponding ignore list.

https://github.com/ChainSafe/lodestar/blob/645d491d49c584a096ee05728e047711c33599f5/packages/api/test/unit/beacon/oapiSpec.test.ts#L87

https://github.com/ChainSafe/lodestar/blob/645d491d49c584a096ee05728e047711c33599f5/packages/api/test/unit/beacon/oapiSpec.test.ts#L108

https://github.com/ChainSafe/lodestar/blob/645d491d49c584a096ee05728e047711c33599f5/packages/api/test/unit/beacon/oapiSpec.test.ts#L155

**Comment by ensi321** [comment]
On a related note, at some point we should update the api error messages to be compliant with the Beacon API spec.

eg.
### [Expected](https://ethereum.github.io/beacon-APIs/#/Beacon/getStateRoot)
```
curl http://localhost:9596/eth/v1/beacon/states/current/root | jq
{
  "code": 400,
  "message": "Invalid state ID: current"
}
```
### Actual
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Invalid block id 'current'"
}
```

### [Expected](https://ethereum.github.io/beacon-APIs/#/Beacon/getPoolAttestations)
```
curl "http://localhost:9596/eth/v1/beacon/pool/attestations?slot=current&committee_index=123" | jq
{
  "code": 400,
  "message": "Invalid slot: current"
}
```
### Actual
```
[
  {
    "instancePath": "/slot",
    "schemaPath": "#/properties/slot/type",
    "keyword": "type",
    "params": {
      "type": "integer"
    },
    "message": "must be integer"
  }
]
```

### [Expected](https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockHeader)
```
curl http://localhost:9596/eth/v1/beacon/headers/123 | jq
{
  "code": 404,
  "message": "Block not found"
}
```
### Actual
```
{
  "statusCode": 404,
  "error": "Not Found",
  "message": "No block found for id '123'"
}
```

**Comment by nflaig** [comment]
> On a related note, at some point we should update the api error messages to be compliant with the Beacon API spec.

I have looked at this before, it should be possible to transform the error before we send it
https://github.com/ChainSafe/lodestar/blob/54e8c4509b1ada622ebeac9dd7954c8bb1e8932f/packages/beacon-node/src/api/rest/base.ts#L67

Regarding the `statusCode` property, this is something fastify sets internally as well I did not find a good way to customize this. e.g. is even hard coded here, I don't think we can override those (other than adding custom default error handler)
[fastify.js#L687-L711](https://github.com/fastify/fastify/blob/e3a07eaa444d0e769802195816d4e1718c2fc9ea/fastify.js#L687-L711)
```js
body = `{"error":"${errorStatus}","message":"Client Timeout","statusCode":408}`
```

In case of default json schema error, would have to compile it in a single messages maybe something like
```js
const { instancePath, message } = errors[0]
const message = `${instancePath.substring(instancePath.lastIndexOf("/") + 1)} ${message}`
```

Even though it would be good if we can support all properties I don't think anyone is actually looking at the json body of an error (unless API is used manually). Most important is the http status code and also `res.text` as this is used in Lodestar to display the error message.
https://github.com/ChainSafe/lodestar/blob/71160df1c3d930285ad5ef2fa7f162d7a1fcfdeb/packages/api/src/utils/client/httpClient.ts#L312-L313

**Comment by wemeetagain** [comment]
There's a 3.0.0-alpha.6 https://github.com/ethereum/beacon-APIs/releases
Do we want to target 3.0.0 instead?

**Comment by nflaig** [comment]
> Do we want to target 3.0.0 instead?

We do already test against that
https://github.com/ChainSafe/lodestar/blob/cf722195b5ebabeb703eb973b2a9b6c70bc32d71/packages/api/test/unit/beacon/oapiSpec.test.ts#L23

and we support all newly added apis already, can update this issue once the 3.0.0 release is out (likely shortly before electra fork)

**Comment by nflaig** [comment]
This is more or less complete, we are passing v3.0.0 spec tests in https://github.com/ChainSafe/lodestar/pull/7470. The remaining missing apis can be ignored as those are already deprecated and will be removed in the next major spec release for Fulu.
