### ISSUE TITLE
Lodestar 2023 Q3 Goals

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5751]
_Work in Progress_

Main Focus: DevEx
- [ ] Solid programmatic usage of Lodestar
- [ ] READMEs and examples 
- [ ] CLI usage for experiments and non-staker usage

Documentation - let's expand on this. 

Retain adoption
- [ ] Process all incoming gossip messages (healthy, honest network conditions with) with reasonable latency.
- [ ] Have close to 0 churn in mesh once the node has a stable mesh
- [x] Increase average rated.network effectiveness from 93% -> to node operator average (~95%) #5615
- [ ] Above average timely head of the network
- [ ] https://github.com/ChainSafe/lodestar/issues/5943

Light Clients
- [ ] Publicly available infrastructure for consensus layer arbitrary proofs of any state
- [ ] Prover integration + demo

Network features
- [ ] Develop deneb HF https://github.com/ChainSafe/lodestar/issues/5279
- [ ] In-protocol deposits https://github.com/ChainSafe/lodestar/issues/5366
- [ ] Verkle tracker issue

Misc / optimizations / debt
- [ ] Good altruistic network peer (fast forward times, back-fill)
- [ ] Dashboard + Metrics Review
  - Inventory our metrics + dashboards with a goal to be more clear about what we're trying to do.

**Comment by philknows** [comment]
Will be superseded by new goals.
