### ISSUE TITLE
Block proposal improvement tracker

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#5823]
tacker for various items to make block production more robust

- [ ] register fee recipients to all fallback bs for the VC
- [x] https://github.com/ChainSafe/lodestar/pull/5831
- [ ] for the multiple fallback bns, resolve with the most successful blinded block, similarly check for the bns
  -  the block production should be multiple bn aware rather than fallback urls handled in httpClient  
- [x] https://github.com/ChainSafe/lodestar/pull/5880 
  - switch to produce block v3 
  - move the execution blinded race to the beacon
- [x] https://github.com/ChainSafe/lodestar/pull/6227
   -  allow execution block to send a blinded response for block production for low latency in publishing 
   - may be full body could be blinded than just the execution pa
   -  respond with a blocksource response for bn to know if the blinded produced block is bound to a bn or not 
- [x] https://github.com/ChainSafe/lodestar/pull/6236
- [x] https://github.com/ChainSafe/lodestar/issues/5826

**Comment by philknows** [comment]
Can you update this issue with the latest status? 🙏

**Comment by g11tech** [comment]
updated, will continue on this post latest changes are PRed for the deneb ... affects produce/publish api all over

**Comment by wemeetagain** [comment]
@g11tech is this fully resolved?
