### ISSUE TITLE
Update to v0.9.3 spec

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#613]
See https://github.com/ethereum/eth2.0-specs/releases

### Beacon chain

- [x] remove signing_root and add explicit signed message containers (ethereum/eth2.0-specs#1491)
- [x] ensure attestation slot and target epoch are coherent (ethereum/eth2.0-specs#1509)
- [x] fix activation queue rate and enforce only activate upon finality (ethereum/eth2.0-specs#1514)
- [x] disallow duplicate indices in indexed attestation (ethereum/eth2.0-specs#1516)
- [x] additional proposer tests for increased coverage (ethereum/eth2.0-specs#1518)

### Fork choice

- [x] remove duplicate validation in on_attestation (ethereum/eth2.0-specs#1492)
- [x] filter out non-viable branches when call to get_head (ethereum/eth2.0-specs#1495)
- [x] clean up handle of slots (ethereum/eth2.0-specs#1510)
- [x] ensure best_justified_checkpoint updates to the best available (ethereum/eth2.0-specs#1508)
- [x] ensure attestation slot and target epoch are coherent (ethereum/eth2.0-specs#1509)

### Simple Serialize

- [x] remove signing_root (ethereum/eth2.0-specs#1491)

**Comment by twoeths** [comment]
The `ensure attestation slot and target epoch are coherent` issue was closed in https://github.com/ChainSafe/lodestar/issues/640

**Comment by twoeths** [comment]
https://github.com/ChainSafe/lodestar/issues/637 is the last issue in v0.9.3 so I think this one is done.
