### ISSUE TITLE
Update to v0.9.4 spec

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#615]
See https://github.com/ethereum/eth2.0-specs/releases

### Validator
- [ ] modifications to support new ENR attesation subnet bitfield (#1534)

### Networking

- [ ] add ENR attestation subnet (attnets) bitfield (ethereum/eth2.0-specs#1534)
- [x] override default libp2p pubsub message-id to be content-addressed (ethereum/eth2.0-specs#1538)
- [x] add quick clarifying note on STATUS message (ethereum/eth2.0-specs#1540)

**Comment by mpetrunic** [comment]
Can we open separate issue for ENR and put it on-ice and set discv5 as blocker?

**Comment by wemeetagain** [comment]
#642
