### ISSUE TITLE
Electra tracker

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#6341]
# Electra Implementations

## EIP-6110 Supply validator deposits on chain
- [ ] Optimize `effectiveBalanceIncrements` fix
- [x] Implement eth1 poll deprecation on hard fork transition #7414 
- [x] Remove unfinalized pubkey cache #7230 

## EIP-7251 Increase the MAX_EFFECTIVE_BALANCE
- [ ] Handle deprecation of `activationChurnLimit`, `exitQueueEpoch` and `exitQueueChurn` in EpochCache

## EIP-7549 Move committee index outside Attestation
- [x] Attestation APIs #6895
- [x] ~~Op pool to drop pre-electra objects during electra activation (need to re-assess if this is needed)~~ not needed, we filter those out in the api response and eventually those will be pruned out

## Blobs
- [x] Uncouple blob limits per block #7176
- [x] Make MAX_REQUEST_BLOB_SIDECARS and MAX_BLOBS_PER_BLOCK configurable #7172  
- [x] Implement engine_getBlobsV1 #7134 

## ~~EIP-7594 PeerDAS~~
- [ ] ~~Basic feature implementation #6353~~

## General
- [ ] Revisit Electra sim test https://github.com/ChainSafe/lodestar/issues/7604
- [x] Finish up unit test for light client #7187

**Comment by philknows** [comment]
https://github.com/ethereum/consensus-specs/pull/3882 is now merged!

**Comment by twoeths** [comment]
lodestar may potentially get performance issue with very long pending balance deposit queue see https://notes.ethereum.org/@ethpandaops/pectra-big-queue-test

this will likely be resolved with batch hash tree root #6939

**Comment by philknows** [comment]
@g11tech @ensi321 , please clean up and/or we can close this issue and only include any additional requirements for alpha.9+ specs

**Comment by nflaig** [comment]
> Handle deprecation of activationChurnLimit, exitQueueEpoch and exitQueueChurn in EpochCache

seems relevant? cc @ensi321, could add that to the clean up list https://github.com/ChainSafe/lodestar/issues/7682

**Comment by g11tech** [comment]
we should close this and restart independent issues if need completion (closing open the tracker if you disagree)
