### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#6358]
### Describe the bug

There are some flaky tests needed be fixed.

- [x] [test/unit/utils/clock.test.ts > util / Clock > getCurrentSlot > 'should return next slot after 11.5s'](https://github.com/ChainSafe/lodestar/actions/runs/7652507863/job/20852823580#step:6:714)
- [x] [test/e2e/network/gossipsub.test.ts > gossipsub / worker > Publish and receive a blsToExecutionChange](https://github.com/ChainSafe/lodestar/actions/runs/7652507863/job/20852770547#step:6:3890)
- [ ] [test/e2e/api/impl/lightclient/endpoint.test.ts > lightclient api > getOptimisticUpdate()](https://github.com/ChainSafe/lodestar/actions/runs/7855861634/job/21438200871?pr=6417#step:6:4190)
- [x] [test/e2e/network/reqresp.test.ts > network / reqresp / worker > Sleep infinite on first byte](https://github.com/ChainSafe/lodestar/actions/runs/7671034884/job/20908688781#step:6:3946)
- [x] [test/e2e/network/reqresp.test.ts > network / reqresp / worker > Sleep infinite on second response chunk](https://github.com/ChainSafe/lodestar/actions/runs/7671034884/job/20908688781#step:6:3960)
- [ ] [test/e2e/sync/unknownBlockSync.test.ts > sync / unknown block sync > should do an unknown block parent sync from another BN](https://github.com/ChainSafe/lodestar/actions/runs/7671034884/job/20908688781#step:6:3914)
- [x] [test/e2e/network/gossipsub.test.ts > gossipsub / worker > Publish and receive a voluntaryExit](https://github.com/ChainSafe/lodestar/actions/runs/7687085125/job/20946738011?pr=6363#step:6:3964)
- [x] [ test/e2e/network/gossipsub.test.ts > gossipsub / worker > Publish and receive a LightClientFinalityUpdate](https://github.com/ChainSafe/lodestar/actions/runs/7687085125/job/20946738011?pr=6363#step:6:3965)
- [ ] [test/e2e/sync/unknownBlockSync.test.ts > sync / unknown block sync > should do an unknown block parent sync from another BN](https://github.com/ChainSafe/lodestar/actions/runs/7687085125/job/20946738011?pr=6363#step:6:3981)
- [x] [test/e2e/network/reqresp.test.ts > network / reqresp / worker > trigger a RESP_TIMEOUT error](https://github.com/ChainSafe/lodestar/actions/runs/7687451427/job/20947518693#step:6:3927)
- [x] [test/e2e/network/reqresp.test.ts > network / reqresp / worker > should send/receive a light client update message](https://github.com/ChainSafe/lodestar/actions/runs/7628049759/job/20778285481?pr=6344#step:6:219)
- [x] [test/unit/beacon/genericServerTest/config.test.ts > beacon / config > Run generic server test](https://github.com/ChainSafe/lodestar/actions/runs/7698507615/job/20978169368?pr=6241#step:6:497)
- [x] Few E2E test failing with `Error: Too many messages for missing streams) not instanceof LodestarError: Error: Too many messages for missing streams` Related to https://github.com/libp2p/js-libp2p/pull/2387
- [ ] [Error: Couldn't find a matching chrome browser for tag "123.0.6290.0" on platform "linux"](https://github.com/ChainSafe/lodestar/actions/runs/7847020467/job/21416404814?pr=6415#step:7:70)
- [ ] [test/unit/sanityCheck.test.ts](https://github.com/ChainSafe/lodestar/actions/runs/14709617547/job/41278936158?pr=7665#step:5:1652)
- [x] [AxiosError: Request failed with status code 429](https://github.com/ChainSafe/lodestar/actions/runs/14731164867/job/41349996153?pr=7762#step:6:10755)

### Expected behavior

All tests should behave as stable they could. 

### Steps to reproduce

- Run all tests

### Additional context

During CI runs on different PRs we found few 

### Operating system

Linux

### Lodestar version or commit hash

unstable

**Comment by twoeths** [comment]
A lot of failed tests happen with `useWorker=true`, I think it has something to do with the fact that vitest also run in worker thread
for gossipsub, I suggest to only run on main thread mode for CI in https://github.com/ChainSafe/lodestar/pull/6368
we could do the same thing in req/resp tests too

I used to be able to stabalize e2e tests in "n-historical" state branch by only use `useWorker=false`

**Comment by nazarhussain** [comment]
> A lot of failed tests happen with `useWorker=true`, I think it has something to do with the fact that vitest also run in worker thread

For this reason we already run e2e tests with forks not threads. 
https://github.com/ChainSafe/lodestar/blob/d6a7a3982b3a0dea9abda3ed8cb6e459d8620c31/vitest.base.e2e.config.ts#L11

**Comment by wemeetagain** [comment]
Sometimes the sim tests still fail on unrelated changes:
- https://github.com/ChainSafe/lodestar/actions/runs/7688253188/job/20949254918?pr=6363
- https://github.com/ChainSafe/lodestar/actions/runs/7694591367/job/20980159851?pr=6369
- https://github.com/ChainSafe/lodestar/actions/runs/7690018577/job/20953270893?pr=6364

**Comment by jeluard** [comment]
Not directly a sim test error, but somewhat related: [Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run](https://github.com/ChainSafe/lodestar/actions/runs/7842300129/job/21400351706#step:19:20)

**Comment by nflaig** [comment]
> Not directly a sim test error, but somewhat related: [Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run](https://github.com/ChainSafe/lodestar/actions/runs/7842300129/job/21400351706#step:19:20)

This happens since we merged https://github.com/ChainSafe/lodestar/pull/6410, the CI failed on that PR as well...

**Comment by nflaig** [comment]
Sim merge tests keep getting stuck and time out after 6h since we merged https://github.com/ChainSafe/lodestar/pull/6344 (as I noted already in the PR), see recent runs on unstable branch ([1](https://github.com/ChainSafe/lodestar/actions/runs/8056718705/job/22006366528#step:15:6025), [2](https://github.com/ChainSafe/lodestar/actions/runs/8051995847/job/21991162221#step:15:6021)).

**Comment by nflaig** [comment]
The browser tests keep failing due to different reasons, this one looks like a race condition ([failed run](https://github.com/ChainSafe/lodestar/actions/runs/8589475783/job/23536119752?pr=6648#step:6:94))? The file has a test suite defined and it passes most of the time. 
> @lodestar/utils: ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
@lodestar/utils:  FAIL  test/unit/err.test.ts [ test/unit/err.test.ts ]
@lodestar/utils: Error: No test suite found in file /home/runner/actions-runner/_work/lodestar/lodestar/packages/utils/test/unit/err.test.ts
@lodestar/utils: ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯


I would suggest we disable browser tests for now as they don't provide any value like this, and are just annoying to deal with

**Comment by nflaig** [comment]
> [test/unit/utils/clock.test.ts > util / Clock > getCurrentSlot > 'should return next slot after 11.5s'](https://github.com/ChainSafe/lodestar/actions/runs/7652507863/job/20852823580#step:6:714)

Interestingly I have not seen that one in a while, maybe related to updating vitest? Vitest seems to have some internal issues with timings in general and fails to execute tests deterministically..hope they can improve this in the future

**Comment by wemeetagain** [comment]
@nazarhussain is this still an issue?

**Comment by nazarhussain** [comment]
@wemeetagain  Not all, but I have seen `e2e: lightclient api > getOptimisticUpdate()` to be failing sometime.

Will need to review each case explicitly in past runs and check these out.

**Comment by nazarhussain** [comment]
Seems the fixes for  [AxiosError: Request failed with status code 429](https://github.com/ChainSafe/lodestar/actions/runs/14731164867/job/41349996153?pr=7762#step:6:10755) does not actually work well. 

https://github.com/ChainSafe/lodestar/actions/runs/14884621520/job/41801270298?pr=7803#step:6:10892
