### ISSUE TITLE
Stale PR Cleanup on External repos

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#6494]
Goal of this issue is to track and resolve PRs located in external repos managed by Lodestar.

## [as-chacha20poly1305](https://github.com/ChainSafe/as-chacha20poly1305/pulls)
- [x] https://github.com/ChainSafe/as-chacha20poly1305/pull/3
- [x] https://github.com/ChainSafe/as-chacha20poly1305/pull/4
- [x] https://github.com/ChainSafe/as-chacha20poly1305/pull/5
- [x] https://github.com/ChainSafe/as-chacha20poly1305/pull/6
- [x] https://github.com/ChainSafe/as-chacha20poly1305/pull/7

## [bls](https://github.com/ChainSafe/bls/pulls)
- [ ] https://github.com/ChainSafe/bls/pull/66
- [ ] https://github.com/ChainSafe/bls/pull/141
- [ ] https://github.com/ChainSafe/bls/pull/142
- [ ] https://github.com/ChainSafe/bls/pull/143
- [ ] https://github.com/ChainSafe/bls/pull/144
- [ ] https://github.com/ChainSafe/bls/pull/145
- [ ] https://github.com/ChainSafe/bls/pull/146
- [ ] https://github.com/ChainSafe/bls/pull/147

## [bls-keygen](https://github.com/ChainSafe/bls-keygen/pulls)
- [ ] https://github.com/ChainSafe/bls-keygen/pull/14

## [bls-keygen-app](https://github.com/ChainSafe/bls-keygen-app/pulls)
- [ ] https://github.com/ChainSafe/bls-keygen-app/pull/26
- [ ] https://github.com/ChainSafe/bls-keygen-app/pull/45
- [ ] https://github.com/ChainSafe/bls-keygen-app/pull/46
- [ ] https://github.com/ChainSafe/bls-keygen-app/pull/47
- [ ] https://github.com/ChainSafe/bls-keygen-app/pull/49
- [ ] https://github.com/ChainSafe/bls-keygen-app/pull/52
- [ ] https://github.com/ChainSafe/bls-keygen-app/pull/53

## [bls-keystore](https://github.com/ChainSafe/bls-keystore/pulls)
- [ ] https://github.com/ChainSafe/bls-keystore/pull/50
- [ ] https://github.com/ChainSafe/bls-keystore/pull/51
- [ ] https://github.com/ChainSafe/bls-keystore/pull/52
- [ ] https://github.com/ChainSafe/bls-keystore/pull/53
- [ ] https://github.com/ChainSafe/bls-keystore/pull/54
- [ ] https://github.com/ChainSafe/bls-keystore/pull/55
- [ ] https://github.com/ChainSafe/bls-keystore/pull/56

## [blst-ts](https://github.com/ChainSafe/blst-ts/pulls)
- [ ] https://github.com/ChainSafe/blst-ts/pull/63

## [discv5](https://github.com/ChainSafe/discv5/pulls)
- [ ] https://github.com/ChainSafe/discv5/pull/197
- [ ] https://github.com/ChainSafe/discv5/pull/228
- [ ] https://github.com/ChainSafe/discv5/pull/231
- [ ] https://github.com/ChainSafe/discv5/pull/232
- [ ] https://github.com/ChainSafe/discv5/pull/237
- [ ] https://github.com/ChainSafe/discv5/pull/243
- [ ] https://github.com/ChainSafe/discv5/pull/244

## [discv5-cli](https://github.com/ChainSafe/discv5-cli)
- [ ] https://github.com/ChainSafe/discv5-cli/pull/9
- [ ] https://github.com/ChainSafe/discv5-cli/pull/12
- [ ] https://github.com/ChainSafe/discv5-cli/pull/15
- [ ] https://github.com/ChainSafe/discv5-cli/pull/25
- [ ] https://github.com/ChainSafe/discv5-cli/pull/26
- [ ] https://github.com/ChainSafe/discv5-cli/pull/27
- [ ] https://github.com/ChainSafe/discv5-cli/pull/28

## [enr-app](https://github.com/ChainSafe/enr-app/pulls)
- [ ] https://github.com/ChainSafe/enr-app/pull/11
- [ ] https://github.com/ChainSafe/enr-app/pull/12
- [ ] https://github.com/ChainSafe/enr-app/pull/19
- [ ] https://github.com/ChainSafe/enr-app/pull/20
- [ ] https://github.com/ChainSafe/enr-app/pull/22
- [ ] https://github.com/ChainSafe/enr-app/pull/25
- [ ] https://github.com/ChainSafe/enr-app/pull/26
- [ ] https://github.com/ChainSafe/enr-app/pull/28
- [ ] https://github.com/ChainSafe/enr-app/pull/33
- [ ] https://github.com/ChainSafe/enr-app/pull/34
- [ ] https://github.com/ChainSafe/enr-app/pull/36
- [ ] https://github.com/ChainSafe/enr-app/pull/37
- [ ] https://github.com/ChainSafe/enr-app/pull/38
- [ ] https://github.com/ChainSafe/enr-app/pull/39
- [ ] https://github.com/ChainSafe/enr-app/pull/40
- [ ] https://github.com/ChainSafe/enr-app/pull/41

## [eth2-light-client-demo](https://github.com/ChainSafe/eth2-light-client-demo/pulls)
- [ ] https://github.com/ChainSafe/eth2-light-client-demo/pull/52
- [ ] https://github.com/ChainSafe/eth2-light-client-demo/pull/53
- [ ] https://github.com/ChainSafe/eth2-light-client-demo/pull/54
- [ ] https://github.com/ChainSafe/eth2-light-client-demo/pull/57
- [ ] https://github.com/ChainSafe/eth2-light-client-demo/pull/59
- [ ] https://github.com/ChainSafe/eth2-light-client-demo/pull/60
- [ ] https://github.com/ChainSafe/eth2-light-client-demo/pull/63
- [ ] https://github.com/ChainSafe/eth2-light-client-demo/pull/64

## [js-libp2p-gossipsub](https://github.com/ChainSafe/js-libp2p-gossipsub/pulls)
- [ ] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/326
- [ ] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/361
- [ ] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/368
- [ ] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/410
- [ ] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/466
- [ ] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/491

## [js-libp2p-noise](https://github.com/ChainSafe/js-libp2p-noise/pulls)
- [ ] https://github.com/ChainSafe/js-libp2p-noise/pull/418

## [ssz](https://github.com/ChainSafe/ssz/pulls)
- [ ] https://github.com/ChainSafe/ssz/pull/271
- [ ] https://github.com/ChainSafe/ssz/pull/274
- [ ] https://github.com/ChainSafe/ssz/pull/278
- [ ] https://github.com/ChainSafe/ssz/pull/281
- [ ] https://github.com/ChainSafe/ssz/pull/282
- [ ] https://github.com/ChainSafe/ssz/pull/284
- [ ] https://github.com/ChainSafe/ssz/pull/285
- [ ] https://github.com/ChainSafe/ssz/pull/287
- [ ] https://github.com/ChainSafe/ssz/pull/295
- [ ] https://github.com/ChainSafe/ssz/pull/305
- [ ] https://github.com/ChainSafe/ssz/pull/306
- [ ] https://github.com/ChainSafe/ssz/pull/328

**Comment by wemeetagain** [comment]
closing as stale
