### ISSUE TITLE
Update to v0.10.0 spec

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#681]
Refer to https://github.com/ethereum/eth2.0-specs/releases

## Beacon chain
- [x] Be more explicit with some bytes-type constants (#1551)
- [x] Allow configuration of genesis fork version to more easily separate testnets (#1554 [note two bugs to this feature fixed in #1556 and #1562])
- [x] Make genesis delay configurable for ease of setting up testnets (#1557)
- [x] Move GENESIS_SLOT/GENESIS_EPOCH to constants as they were not truly configurable in the first place (#1556)
- [x] Add additional Deposit test cases (#1558)
- [x] Very minor cosmetic cleanups. No breaking changes and no renamings! (#1525)

## Validator
- [x] Use timestamp instead of block height in eth1 voting to allow for simpler caching (#1553)
- [ ] Add eager attestation broadcasting to optimize attestation propagation in the normal case (#1555)
## Networking
- [x] Allow empty lists in streamed responses (#1549)
- [x] Validate block not from future slot (and add a small clock disparity allowance) (#1563)

## Deposit contract
- [x] Version bump to integrate a recent fix in the vyper compiler (#1539)

## Simple Serialize
- [x] Rename BytesN to ByteVector and Bytes to ByteList to conform to naming conventions and avoid confusion (#1480)

## BLS
- [x] Integrate IETF BLS standards and use in spec throughout (#1532)

**Comment by aunyks** [comment]
Do the deposit contract and SSZ changes apply to our repos at the moment?

**Comment by wemeetagain** [comment]
@aunyks :+1: we can mark those as "complete"
