### ISSUE TITLE
Migrate missing eslint rules during migration from eslint

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#7150]
### Problem description

Based on the discussion https://github.com/ChainSafe/lodestar/pull/7108#issuecomment-2386606996 there are few eslint rules which don't have alternative biome rules yet. We keep this issue as tracker to migrate those when available, or decide which rules are not useful anymore. 

- [ ] [await-thenable](https://typescript-eslint.io/rules/await-thenable/)
- [ ] [ban-ts-comment](https://typescript-eslint.io/rules/ban-ts-comment/)
- [ ] [explicit-function-return-type](https://typescript-eslint.io/rules/explicit-function-return-type/)
- [ ] [func-call-spacing](https://eslint.org/docs/rules/func-call-spacing)
- [ ] [no-duplicate-enum-values](https://typescript-eslint.io/rules/no-duplicate-enum-values/)
- [ ] [no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises/)
- [ ] [no-non-null-asserted-optional-chain](https://typescript-eslint.io/rules/no-non-null-asserted-optional-chain/)
- [ ] [no-unnecessary-type-assertion](https://typescript-eslint.io/rules/no-unnecessary-type-assertion/)
- [ ] [no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment/)
- [ ] [no-unsafe-call](https://typescript-eslint.io/rules/no-unsafe-call/)
- [ ] [no-unsafe-member-access](https://typescript-eslint.io/rules/no-unsafe-member-access/)
- [ ] [no-unsafe-return](https://typescript-eslint.io/rules/no-unsafe-return/)
- [ ] [no-unused-expressions](https://eslint.org/docs/rules/no-unused-expressions)
- [ ] [no-var-requires](https://typescript-eslint.io/rules/no-var-requires/)
- [ ] [restrict-template-expressions](https://typescript-eslint.io/rules/restrict-template-expressions/)
- [ ] [return-await](https://typescript-eslint.io/rules/return-await/)
- [x] [semi](https://eslint.org/docs/rules/semi)
- [ ] [strict-boolean-expressions](https://typescript-eslint.io/rules/strict-boolean-expressions/)
- [ ] [triple-slash-reference](https://typescript-eslint.io/rules/triple-slash-reference/)
- [ ] [type-annotation-spacing](https://typescript-eslint.io/rules/type-annotation-spacing/)
- [ ] [vitest/consistent-test-it](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/consistent-test-it.md)
- [ ] [vitest/prefer-called-with](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/prefer-called-with.md)
- [ ] [vitest/prefer-spy-on](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/prefer-spy-on.md)
- [ ] [expect-expect](https://eslint.org/docs/rules/expect-expect)
- [ ] [no-identical-title](https://eslint.org/docs/rules/no-identical-title)
- [ ] [no-commented-out-tests](https://eslint.org/docs/rules/no-commented-out-tests)
- [ ] [valid-title](https://eslint.org/docs/rules/valid-title)
- [ ] [valid-expect](https://eslint.org/docs/rules/valid-expect)
- [ ] [valid-describe-callback](https://eslint.org/docs/rules/valid-describe-callback)
- [ ] [require-local-test-context-for-concurrent-snapshots](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/require-local-test-context-for-concurrent-snapshots.md)
- [ ] [no-import-node-test](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/no-import-node-test.md)
- [ ] [func-names](https://eslint.org/docs/rules/func-names)
- [ ] [new-parens](https://eslint.org/docs/rules/new-parens)
- [ ] [no-caller](https://eslint.org/docs/rules/no-caller)
- [ ] [no-delete-var](https://eslint.org/docs/rules/no-delete-var)
- [ ] [no-extra-semi](https://eslint.org/docs/rules/no-extra-semi)
- [ ] [no-mixed-spaces-and-tabs](https://eslint.org/docs/rules/no-mixed-spaces-and-tabs)
- [ ] [no-restricted-syntax](https://eslint.org/docs/rules/no-restricted-syntax)
- [ ] [no-unexpected-multiline](https://eslint.org/docs/rules/no-unexpected-multiline)
- [ ] [no-useless-backreference](https://eslint.org/docs/rules/no-useless-backreference)
- [ ] [object-curly-spacing](https://eslint.org/docs/rules/object-curly-spacing)

### Solution description

There should be no useful rule left out.

**Comment by nazarhussain** [comment]
The `semi` rule is actually a formatting configuration in biomejs, not the lint rule.

https://github.com/ChainSafe/lodestar/blob/a570048187f1e729c0be3939239fcfa3aa0a008e/biome.jsonc#L266

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
