### ISSUE TITLE
Running Lodestar using Bun

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#7280]
Given the findings in https://github.com/ChainSafe/lodestar/issues/7237, we would like to run lodestar using bun.

This is a tracking issue to report / collect problems running lodestar using bun.

See the [`cayman/bun`](https://github.com/ChainSafe/lodestar/tree/cayman/bun) branch

## Issues

- `@chainsafe/prometheus-gc-stats`: `SyntaxError: Export named 'GCProfiler' not found in module 'v8'.`
- failure loading `@chainsafe/blst` `0.2.0` in light-client package
- bytesToInt - `Number(bytesToBigint(...))` returning `0.5`, wtf
- `classic-level`: this stacktrace
```
 ✖ Error
    at dlopen (native)
    at load (/home/cayman/Code/lodestar/node_modules/node-gyp-build/index.js:22:10)
    at <anonymous> (/home/cayman/Code/lodestar/node_modules/classic-level/binding.js:1:8)
    at anonymous (native)
    at <anonymous> (/home/cayman/Code/lodestar/node_modules/classic-level/index.js:7:7)
    at <anonymous> (unknown:11:43)
    at processTicksAndRejections (unknown:7:39)
```

Update
- [ ] https://github.com/ChainSafe/lodestar/issues/7869
- [ ] cannot use bun:ffi async using callback https://github.com/ChainSafe/blst-z/issues/44
- [ ] napi modules are not fully supported, latest issue: https://github.com/oven-sh/bun/issues/19802
- [ ] leveldb binding is erroring
- [ ] https://github.com/ChainSafe/lodestar/issues/8089
- [ ] https://github.com/ChainSafe/lodestar/issues/8518
- [ ] https://github.com/ChainSafe/lodestar/issues/8519
- [ ] https://github.com/ChainSafe/lodestar/issues/8521
- [ ] https://github.com/ChainSafe/lodestar/issues/8524
- [ ] https://github.com/ChainSafe/lodestar/issues/8526

Bun issues
- [ ] https://github.com/oven-sh/bun/issues/23393
- [ ] https://github.com/oven-sh/bun/issues/23686

**Comment by nflaig** [comment]
> we would like to run lodestar using bun

We should look into being able to run Lodestar on bun but I think we need to always be able to run on node or at least have the ability to do so even if it's not our preferred runtime.

Bun is still early and less tested / robust, they also have just one maintainer that does most of the work while node has a huge community and has a much more open development process.

**Comment by wemeetagain** [comment]
>  I think we need to always be able to run on node

I disagree with this on a longer timespan, though for the sake of derisking the experiment, agree it would be helpful to start with being able to switch between runtimes.

Our top-level cli is an opinionated product (tailored for a specific environment), not a vanilla javascript library (that can / should be run on any environment).
So practically, we just want to use whichever runtime(s) helps us achieve our goals. We shouldn't care ideologically about supporting X or Y runtime just to support as many as possible. (Every abstraction has a cost)
(This doesn't apply to our libraries, which _should_ work in any environment)

If, for example, using bun results in a 100% speedup and 50% reduction in memory usage all else the same, we will always use that.

Swappable runtimes will be helpful for derisking a migration, but ongoing maintenance of supporting a runtime needs to be measured against how useful it actually is. I'm saying that if we aren't running it in production, and we aren't shipping it to users, it becomes a vestigial organ that should be harvested the moment it starts to get in the way.

> Bun is still early and less tested / robust

I think we can easily make the case that it is less tested, but I'm not sure the same can be said about robustness. (Depending on how you measure robustness, benchmarks seem show that bun may result in a more robust Lodestar beacon node)
I suppose the more we test it, the more we can assess the robustness.

**Comment by nflaig** [comment]
> I disagree with this on a longer timespan

if bun has a bus factor > 1 at some point then sure

> ongoing maintenance of supporting a runtime needs to be measured against how useful it actually is

yeah that's likely gonna be an issue, we go as far right now that we decided to not even run lodestar on different node versions (although we still allow the previous stable version), but with different runtimes it would be too painful.

My concern would mostly be around investing a lot of time in rewriting everything to Bun FFI which would essentially vendor lock us. And last time I checked bun is still solely VC funded (last round August 2022), they likely will get more funding or potentially grants / donations in the future but that's still an additional risk.

**Comment by matthewkeil** [comment]
I tend to agree with @nflaig on this.  I do not think we should hitch ourselves to Bun.  Utilizing it to its fullest is a great idea but we should not depend/rely on it.  Node has a much more robust development process and will definitely be around for the long haul.  Bun is still relatively new to the JS community.  Its a great project with huge potential but node is tried and true.  We should definitely preserve compatibility with node.

**Comment by twoeths** [comment]
I think for libraries, I agree that we should support both/all javascript runtimes. For beacon-node, it's just nice to support NodeJS, we don't have to

**Comment by philknows** [comment]
I guess what we need to figure out here is what sort of milestones/markers we need to see for: 
- Bun to be out of an experimental phase in Lodestar and supported alongside nodeJS?
- Bun to transition as our primary development runtime?
- Bun to become "mature enough" that we feel like dropping nodeJS support is minimally risky?

> I think for libraries, I agree that we should support both/all javascript runtimes. For beacon-node, it's just nice to support NodeJS, we don't have to

What is the overhead of being able to support both for a transitory period?

**Comment by twoeths** [comment]
> What is the overhead of being able to support both for a transitory period?

@philknows right now we're only at experimental phase, we're not able to run lodestar on Bun yet. We'll consider if it's possible and if it makes sense to support both on the beacon node later

**Comment by twoeths** [comment]
this is blocker of #5857 and https://github.com/ChainSafe/ssz/issues/479

**Comment by twoeths** [comment]
persist the test result with hashtree performance using bun/nodejs napi/bun:ffi [here](https://gist.github.com/twoeths/5d6af2232f1e0566e9bdc4e30e67294c?permalink_comment_id=5690602#gistcomment-5690602)
in summary:
- bun manages memory way better than NodeJS
- bun napi is slower than nodejs napi
- bun:ffi is 2x faster than nodejs:napi

**Comment by twoeths** [comment]
I have 2 branches to call hash() function 2 times at native in [hashtree-js](https://github.com/ChainSafe/hashtree-js/blob/te/benchmark_2x/src/lib.rs#L46) and [hashtree-z](https://github.com/ChainSafe/hashtree-z/blob/te/benchmark_2x/src/root_c_abi.zig#L15)

based on the result specified [here](https://gist.github.com/twoeths/5d6af2232f1e0566e9bdc4e30e67294c?permalink_comment_id=5694871#gistcomment-5694871)

- node napi binding time: 528ms
- node hash time: 70ms
- bun napi binding time: 557ms
- bun hash time: 234ms
- bun ffi binding time: 237ms
- bun ffi hash time: 74ms

we can have some conclusions:
- node napi binding time is 7.5x node hashtree hash() time
- bun napi binding time is a little bit higher than node, but bun hashtree hash() time is 3x slower than node
- bun ffi binding time is 3.2x bun hashtree hash() time
- bun ffi hash time ~= node hashtree hash() time

**Comment by philknows** [comment]
A reminder for us here to re-bench deserializing hex as seen in: https://github.com/ChainSafe/lodestar/pull/8275#issuecomment-3228184163

**Comment by wemeetagain** [comment]
@matthewkeil mentioned:
- does the chrome debugger work with bun?
- how will we do cpu and heap profiling?

**Comment by wemeetagain** [comment]
This issue is visible on a running node:
An uncaught exception, unfortunately the stack trace is not entirely helpful
```
Sep-23 17:54:50.121[network]         error: uncaughtException: Unhandled error. ([abort@[native code]
onAbort@/home/user/lodestar/node_modules/any-signal/dist/src/index.js:4:21
abort@[native code]
onAbort@/home/user/lodestar/node_modules/@libp2p/utils/dist/src/queue/job.js:29:28] {
  line: 4,
  column: 21,
  sourceURL: '/home/user/lodestar/node_modules/any-signal/dist/src/index.js'
})
Error: Unhandled error. ([abort@[native code]
onAbort@/home/user/lodestar/node_modules/any-signal/dist/src/index.js:4:21
abort@[native code]
onAbort@/home/user/lodestar/node_modules/@libp2p/utils/dist/src/queue/job.js:29:28] {
  line: 4,
  column: 21,
  sourceURL: '/home/user/lodestar/node_modules/any-signal/dist/src/index.js'
})
    at unknown
    at emitError (node:events:60:31)
    at emitErrorNT (internal:streams/destroy:88:12)
    at emitErrorCloseNT (internal:streams/destroy:69:14)
    at processTicksAndRejections (native:7:39) - Unhandled error. ([abort@[native code]
onAbort@/home/user/lodestar/node_modules/any-signal/dist/src/index.js:4:21
abort@[native code]
onAbort@/home/user/lodestar/node_modules/@libp2p/utils/dist/src/queue/job.js:29:28] {
  line: 4,
  column: 21,
  sourceURL: '/home/user/lodestar/node_modules/any-signal/dist/src/index.js'
})
Error: Unhandled error. ([abort@[native code]
onAbort@/home/user/lodestar/node_modules/any-signal/dist/src/index.js:4:21
abort@[native code]
onAbort@/home/user/lodestar/node_modules/@libp2p/utils/dist/src/queue/job.js:29:28] {
  line: 4,
  column: 21,
  sourceURL: '/home/user/lodestar/node_modules/any-signal/dist/src/index.js'
})
    at unknown
    at emitError (node:events:60:31)
    at emitErrorNT (internal:streams/destroy:88:12)
    at emitErrorCloseNT (internal:streams/destroy:69:14)
    at processTicksAndRejections (native:7:39)
```

**Comment by wemeetagain** [comment]
Another:
```
Sep-23 17:58:10.022[]                error: uncaughtException: Closing
Error: Closing
    at destroySocket (/home/user/lodestar/packages/beacon-node/src/api/rest/activeSockets.ts:106:19)
    at terminate (/home/user/lodestar/packages/beacon-node/src/api/rest/activeSockets.ts:81:13)
    at terminate (/home/user/lodestar/packages/beacon-node/src/api/rest/activeSockets.ts:54:35)
    at close (/home/user/lodestar/packages/beacon-node/src/metrics/server/http.ts:102:26)
    at close (/home/user/lodestar/packages/beacon-node/src/metrics/server/http.ts:96:33)
    at close (/home/user/lodestar/packages/beacon-node/src/node/nodejs.ts:339:55)
    at /home/user/lodestar/packages/cli/src/cmds/beacon/handler.ts:140:21
    at processTicksAndRejections (native) - Closing
Error: Closing
    at destroySocket (/home/user/lodestar/packages/beacon-node/src/api/rest/activeSockets.ts:106:19)
    at terminate (/home/user/lodestar/packages/beacon-node/src/api/rest/activeSockets.ts:81:13)
    at terminate (/home/user/lodestar/packages/beacon-node/src/api/rest/activeSockets.ts:54:35)
    at close (/home/user/lodestar/packages/beacon-node/src/metrics/server/http.ts:102:26)
    at close (/home/user/lodestar/packages/beacon-node/src/metrics/server/http.ts:96:33)
    at close (/home/user/lodestar/packages/beacon-node/src/node/nodejs.ts:339:55)
    at /home/user/lodestar/packages/cli/src/cmds/beacon/handler.ts:140:21
    at processTicksAndRejections (native)
```

**Comment by wemeetagain** [comment]
running #8462 

This is a pretty bad issue, The first time I started up the node with an existing database, it started syncing, then stalled. Upon restart, this error happened and the node crashed (and there was a restart loop).

```
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:  ✖ Error: Corruption
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at throwErr (/usr/src/lodestar/node_modules/@lodestar/bun/src/common.ts:6:10)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at dbPut (/usr/src/lodestar/node_modules/@lodestar/bun/src/leveldb.ts:49:2)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at put (/usr/src/lodestar/packages/db/src/controller/level_bun.ts:87:4)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at put (/usr/src/lodestar/packages/db/src/controller/level_bun.ts:83:12)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at putBinary (/usr/src/lodestar/packages/db/src/abstractRepository.ts:73:18)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at putBinary (/usr/src/lodestar/packages/db/src/abstractRepository.ts:72:18)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at persistAnchorState (/usr/src/lodestar/packages/beacon-node/src/chain/initState.ts:66:26)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at persistAnchorState (/usr/src/lodestar/packages/beacon-node/src/chain/initState.ts:37:2)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at checkAndPersistAnchorState (/usr/src/lodestar/packages/beacon-node/src/chain/initState.ts:212:10)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at checkAndPersistAnchorState (/usr/src/lodestar/packages/beacon-node/src/chain/initState.ts:174:2)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at initAndVerifyWeakSubjectivityState (/usr/src/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:74:8)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at initAndVerifyWeakSubjectivityState (/usr/src/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:33:2)
Sep 24 20:57:15 feat2-lg1k-hzax41 beacon_run.sh[612374]:     at processTicksAndRejections (native)
```

**Comment by wemeetagain** [comment]
Appears that sockets are being leaked
`lodestar_api_rest_active_sockets_count`

<img width="956" height="306" alt="Image" src="https://github.com/user-attachments/assets/a1cf7a4c-8e60-4b96-961f-232b05af79ea" />

**Comment by wemeetagain** [comment]
BLS worker latency scaling appears wrong
`rate(lodestar_bls_thread_pool_latency_to_worker_sum[6m])/rate(lodestar_bls_thread_pool_latency_to_worker_count[6m])`
`rate(lodestar_bls_thread_pool_latency_from_worker_sum[6m])/rate(lodestar_bls_thread_pool_latency_from_worker_count[6m])`
<img width="977" height="223" alt="Image" src="https://github.com/user-attachments/assets/1341efcd-02a7-4986-b986-ab436625177c" />

Same with network latency scaling
<img width="961" height="252" alt="Image" src="https://github.com/user-attachments/assets/4d7ac39e-a43c-4734-99ad-960d956778ad" />

**Comment by wemeetagain** [comment]
> Appears that sockets are being leaked `lodestar_api_rest_active_sockets_count`
> <img alt="Image" width="956" height="306" src="https://private-user-images.githubusercontent.com/1348242/493584315-a1cf7a4c-8e60-4b96-961f-232b05af79ea.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkyNjgwNzgsIm5iZiI6MTc1OTI2Nzc3OCwicGF0aCI6Ii8xMzQ4MjQyLzQ5MzU4NDMxNS1hMWNmN2E0Yy04ZTYwLTRiOTYtOTYxZi0yMzJiMDVhZjc5ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MzBUMjEyOTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBkNjVmYjAyNjQxZjkzNzJmNDJkZDY3MjRiN2U0OWM3NGE0ZmMzYjFlZDUyODZiNDJjYWFlN2ZlMzQ4NDg5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.DjFMfsoI6SvyrOdTD98WA8jIZVs75fZqxe6eQiZj1Aw">

Fixed by the latest bun release 🚀 1.2.23

**Comment by wemeetagain** [comment]
closing as stale
