### ISSUE TITLE
Tests for state transition helpers

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#87]
There are still many tests that need to be written -- If you plan to work on any just comment in the issue.

I will be working top to bottom (of this list) -- theres a lot of low hanging fruit for anyone that wants to dive into the code.

There are a lot of test, rather than writing a 10,000 line file - I'm opting for a file by function structure for the tests.

- [ ] ~hash~ **Ignore, no test needed at this time**
- [ ] hashTreeRoot
- [x] ~slotToEpoch~
- [ ] getPreviousEpoch **Blocked by #86**
- [ ] ~getCurrentEpoch~ **Ignore, implicitly tested with slotToEpoch**
- [x] ~getEpochStartSlot~
- [x] ~isActiveValidator~
- [x] ~getActiveValidatorIndices~ **Implemented from old spec, needs to be updated**
- [ ] getPermutedIndex
- [x] ~split~
- [x] ~getEpochCommitteeCount **(PR: #97)**~
- [ ] getShuffling
- [ ] getPreviousEpochCommitteeCount
- [ ] getCurrentEpochCommitteeCount
- [ ] getNextEpochCommitteeCount
- [ ] getCrosslinkCommittessAtSlot
- [ ] getBlockRoot **WIP (david)**
- [ ] getRandaoMix
- [ ] getActiveIndexRoot
- [ ] generateRoot **Blocked by #86**
- [ ] getBeaconProposerIndex
- [x] ~merkleRoot~
- [ ] getAttestationParticipants
- [x] ~isPowerOfTwo~
- [ ] intToBytes1, intToBytes2... (to be handled by Buffer) **WIP (david)**
- [ ] bytesToInt (to be handled by Buffer) **Blocked by #86**
- [ ] getEffectiveBalance
- [ ] getTotalBalance
- [x] ~getForkVersion **(pr: #99)**~
- [x] ~getDomain **(pr: #99)**~
- [x] ~getBitfieldBit~
- [ ] verifyBitfield **Blocked by #86**
- [ ] verifySlashableAttestation **Blocked by #86**
- [x] ~isDoubleVote **(pr: #93)**~
- [x] ~isSurroundVote **(pr: #100)**~
- [x] ~integerSquareRoot (intSqrt)~
- [ ] getEntryExitEffectEpoch
- [x] blsVerify **Blocked by #86**
- [x] blsVerifyMultiple
- [x] blsAggregatePubkeys
- [ ] validateProofOfPossession
- [ ] processDeposit

**Comment by GregTheGreek** [comment]
An upcoming pr will introduce a utils dir under `tests/utils` that has a few usefull functions thus far:
validator.ts:
- generateValidator()
- generateValidators(n:number)

**Comment by wemeetagain** [comment]
upcoming pr for getEpochCommitteeCount

**Comment by GregTheGreek** [comment]
In the process of making `beaconState` generators. Not associated to a test yet.

**Comment by GregTheGreek** [comment]
Working on `getForkVersion()` and `getDomain()`

**Comment by ansermino** [comment]
Updated to latest spec, specifically to reflect #86 and the current state of the tests

**Comment by GregTheGreek** [comment]
@ansermino merci david

**Comment by johnsBeharry** [comment]
is this issue up to date? @GregTheGreek

**Comment by GregTheGreek** [comment]
@johnsbeharry as of a day or two ago no, #237 addresses this!
